### ISSUE TITLE
New website? Also long wait time to open up websites

### ISSUE THREAD

**Issue by Tylerodi** [QuiteAFancyEmerald/HolyUnblockerPublic#164]
Hey I been using Iboss.school and I love it but whenever I try to open up tinder and Twitter and takes forever to load and stays on the Home Screen. Can y’all fix this?

**Comment by QuiteAFancyEmerald** [comment]
I don't own Hypertabs lol
Open an issue regarding this on the official Corrosion repo though since this relates to that
