### ISSUE TITLE
Proxy Question

### ISSUE THREAD

**Issue by vackyton** [QuiteAFancyEmerald/HolyUnblockerPublic#167]
Sooooo..... I was wondering how your proxies work and how to make them and could you make a video since i am not that good at stuff but i can make a virus in python thats kinda it and also a webpage.

**Comment by QuiteAFancyEmerald** [comment]
Maybe talk about this more in the TN discord since you are more likely to get an in-depth convo there :)

**Comment by vackyton** [comment]
alr
