### ISSUE TITLE
GBA Emulator Issue

### ISSUE THREAD

**Issue by ShinyMudkip13** [QuiteAFancyEmerald/HolyUnblockerPublic#174]
Hi! I have been using the GBA emulator available on Holy Unblocker, but recently it has stopped working with the program getting stuck on the "Loading Getting Assets" screen prior to the game booting up. I tested this on several computers and the issue prevails. Am I doing something wrong or is it an issue within the system? Thanks in advance for any help!

**Comment by SplitSplice** [comment]
Had the same problem, but it would just show a black screen.

**Comment by nevr13** [comment]
this issue is being addresed.

**Comment by Nebelung-Dev** [comment]
From the discord

Quite A Fancy Emerald#0001:
@Proxy Ping I am aware that the Emulator/EmuLibrary pages on Holy Unblocker are currently not working. Simply just messed up something with caching and will fix it soon

**Comment by QuiteAFancyEmerald** [comment]
Resolved
