### ISSUE TITLE
hcaptcha dont work

### ISSUE THREAD

**Issue by s191ed** [QuiteAFancyEmerald/HolyUnblockerPublic#175]
hcaptcha dosent show up whenever i try to login in discord
![image](https://user-images.githubusercontent.com/74692343/138205547-fad091ef-9ca6-4fdf-81c6-ddbca6c12c91.png)

**Comment by nanospearing** [comment]
Have you try womgnix? That has very good support for that stuff. Also you can just use the QR code.

**Comment by s191ed** [comment]
![image](https://user-images.githubusercontent.com/74692343/138302108-6e30469f-9759-4d35-ac13-1b7fafe2f933.png)
yep, it dosent even load. also  the QR code dosent load (it just infinitely loads)

**Comment by nanospearing** [comment]
So I see what’s wrong now, you are self hosting. I would recommend grabbing a link from their discord server if you want this to work fully, I have tried to setup womgnix but it is very complicated to get up and run.

**Comment by s191ed** [comment]
alright thanks 👍
