### ISSUE TITLE
Game Request: Minecraft/Webmc

### ISSUE THREAD

**Issue by artiomvisc** [QuiteAFancyEmerald/HolyUnblockerPublic#177]
https://minecraft.js.org/ https://github.com/michaljaz/webmc
Good replacement for the existing Minecraft Javascript in the games section. Has functional multiplayer (cracked servers only).

**Comment by softsheep6** [comment]
yes pls add this

**Comment by QuiteAFancyEmerald** [comment]
Hmmm this requires a bit more setup than the majority of games featured on Holy Unblocker and its rather resource intensive so I'll consider it. Note that I'm not really prioritizing game requests :(
