### ISSUE TITLE
when i try to deploy Holy-Unblocker to heroku, only one unblocker works. all of the other ones says error, when i click on each button.

### ISSUE THREAD

**Issue by Quart2629** [QuiteAFancyEmerald/HolyUnblockerPublic#184]

**Comment by Nebelung-Dev** [comment]
You need a subdomain for Womginx or PyDodge. Please see [this](https://github.com/titaniumnetwork-dev/Holy-Unblocker#an-explanation-for-beginners-with-external-proxies-and-hosting) for more info

**Comment by QuiteAFancyEmerald** [comment]
Yeah you didn't setup any of the external proxies correctly. Note that it specifically states that only Corrosion/Alloy is hosted locally with this repo. Regarding the rest look into the README for a detailed setup guide when it comes to externally hosted proxies.
