### ISSUE TITLE
Fix binding of isaac.

### ISSUE THREAD

**Issue by OctoRocket** [QuiteAFancyEmerald/HolyUnblockerPublic#186]
The binding of isaac doesn't work
![Screenshot 2021-10-27 171752](https://user-images.githubusercontent.com/88291550/139155408-cd8f2087-9d7f-4bb3-afce-f25ef4750a73.png)

**Comment by Nebelung-Dev** [comment]
The file size is too big
Error: File size exceeded the configured limit of 20 MB.

**Comment by QuiteAFancyEmerald** [comment]
@BinBashBanana

**Comment by QuiteAFancyEmerald** [comment]
I haven't seen this issue before so huh

**Comment by BinBashBanana** [comment]
I might add a second fetch try, so if JSDelivr fails, it will use GitHub's builtin CDN as a backup.
