### ISSUE TITLE
Discord vc / instagram issue

### ISSUE THREAD

**Issue by gigibutbetter** [QuiteAFancyEmerald/HolyUnblockerPublic#188]
The Discord Vc isnt accessible, and i cant get a vpn so i can do calls, cus ill have ppl texting me asking to do a vc in the middle of class, which i could totally do, i just can never get the vc to connect. It wont even let me enable access to my mic and camera.
Another thing i wanted to point out was that on instagram, a lot of features are still locked. I was able to access it via the site proxy that starts with a w, its just hard to click on certain parts of instagram, like itll notify me when i have a message, but i cant read my messages, it'll just stay stuck in the blank loading screen. I also cant view any notifications on if i got a like or a follow.all i can currently do on there is scroll thru the posts, and every once and a while, actually play a video.
But im new to this and i think what u guys are doing is really smart and hella cool homies! Especially when i noticed the customization tab thingy, it just takes a while to load, but I'm already in love!
Love you guys!!!

**Comment by QuiteAFancyEmerald** [comment]
Open/create this issue on the official Corrosion repository if one isn't open already! :)

**Comment by QuiteAFancyEmerald** [comment]
Glad you like Holy Unblocker but those issues mostly refer to Corrosion or Womginx.

Holy Unblocker = Proxy service/site
Corrosion/PyDodge/Womginx = Web proxies

Super sorry though <3
