### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Rockpods** [QuiteAFancyEmerald/HolyUnblockerPublic#191]
I am compiling a list of all of the open bug reports for Holy Unblocker. It will be categorized by needs more info, known bug, assumptions, and useful. If there is sufficient evidence to semi-accurately guess what problem there is it will be an assumption. If there is a lot of evidence then it will be classified as useful. If it says needs more info then it means that the bug report needs more information to be useful. If it says known bug then that means that Emerald was aware of the bug at the time of posting.

Formating:
(Number from newest): (Name of issue) - (link to screenshots if provided)
More Info: Pre-existing info I have or extra info provided by issue creator
NOTES: RESPONSE FROM EMERALD TO REQUEST
Link: Link to the issue

**Useful:**
1.

**Known Bug**
1. GBA Emulator Issue
More Info: Hi! I have been using the GBA emulator available on Holy Unblocker, but recently it has stopped working with the program getting stuck on the "Loading Getting Assets" screen prior to the game booting up. I tested this on several computers and the issue prevails. Am I doing something wrong or is it an issue within the system? Thanks in advance for any help!
NOTES: (Unofficial response from Nebelung) "From the discord
Quite A Fancy Emerald#1:
@Proxy Ping I am aware that the Emulator/EmuLibrary pages on Holy Unblocker are currently not working. Simply just messed up something with caching and will fix it soon"
Link: https://github.com/titaniumnetwork-dev/Holy-Unblocker/issues/174

**Needs More Info**
1. YouTube issue
More Info: None provided but it may have just been confusion because corrosion was slow.
NOTES: Can you explain a bit more? Corrosion seems to be working for me despite it being terribly slow (an issue that I am working on atm)
Link: https://github.com/titaniumnetwork-dev/Holy-Unblocker/issues/185

**Resolved**
1. Too Many Redirects
More info: I'd like to add to this issue, most instances of holy unblocker have an issue saying "[proxy link] redirected you too many times" and it tells you to clear cookies, did that and it didn't work. I also Ctrl+Shift+R'd it and also didn't work. Could you also take a look at this?
NOTES: (ROCKPODS) What website are you trying to access
Link: https://github.com/titaniumnetwork-dev/Holy-Unblocker/issues/191#issuecomment-956483585

**Comment by MrBrastavaya** [comment]
I'd like to add to this issue, most instances of holy unblocker have an issue saying "[proxy link] redirected you too many times" and it tells you to clear cookies, did that and it didn't work. I also Ctrl+Shift+R'd it and also didn't work. Could you also take a look at this?

**Comment by Rockpods** [comment]
What website are you trying to access?  I am not sure if this is relevant but it would be nice to know.

**Comment by MrBrastavaya** [comment]
It is (in the photo)

> What website are you trying to access? I am not sure if this is relevant but it would be nice to know.

![Screenshot 2021-11-01 4 08 50 PM](https://user-images.githubusercontent.com/88563252/139753777-faf2548f-4768-4658-b959-b4c889721f19.png)
it only does it on womginx too

**Comment by QuiteAFancyEmerald** [comment]
@MrBrastavaya Should be resolved now! Sorry about that. The above actually was an issue with CF on that domain, not Womginx :D

**Comment by MrBrastavaya** [comment]
@QuiteAFancyEmerald Thank You!

**Comment by s191ed** [comment]
![image](https://user-images.githubusercontent.com/74692343/142096100-b7a09894-cb79-481a-857f-51402f8e2906.png)
bruh discord dosent work, youtube dosent work, im using the same link mrbrastavaya used @QuiteAFancyEmerald

**Comment by MrBrastavaya** [comment]
@s191ed I would ask @QuiteAFancyEmerald as my friend just gave me a hack that instantly removes all filters from my Chromebook like scum. Though, I have been noticing sudden degradation on that instance.
