### ISSUE TITLE
FEATURE REQUEST: Instructions for integrating proxy sites to a public instance.

### ISSUE THREAD

**Issue by foxsouns** [QuiteAFancyEmerald/HolyUnblockerPublic#192]
I've got a working instance, but can't wrap my head around how I am supposed to implement the proxies. Wanted some help on this, and maybe have this help implemented into the README.md. Thank you in advance!

**Comment by foxsouns** [comment]
Seems like it's a drag and drop to `src/`? Do I need to change names? Do I mess with npm at all?

**Comment by QuiteAFancyEmerald** [comment]
Nope! You just need to setup each external proxy on a separate subdomain and be using something like NGINX as a reverse proxy.
I'll maybe updated the README later to include said steps but look over #19 or the Corrosion README.

**Comment by foxsouns** [comment]
thank you! i guess this should be kept open as a reminder, but otherwise i guess this is done.
