### ISSUE TITLE
Holy Unblocked is blocked

### ISSUE THREAD

**Issue by ghost** [QuiteAFancyEmerald/HolyUnblockerPublic#193]
Holy Unblocked is blockedHoly Unblocked is blockedHoly Unblocked is blockedHoly Unblocked is blockedHoly Unblocked is blockedHoly Unblocked is blockedHoly Unblocked is blockedHoly Unblocked is blockedHoly Unblocked is blockedHoly Unblocked is blockedHoly Unblocked is blocked

**Comment by MrBrastavaya** [comment]
Join the discord for more links by typing %proxy to the bot channel.

**Comment by ghost** [comment]
could you send the links

**Comment by MrBrastavaya** [comment]
@ZombiefiedGaming unfortunately sending links ends up in them getting blocked faster, so just join the discord. 
Refer to #44

**Comment by ghost** [comment]
![Screenshot (137)](https://user-images.githubusercontent.com/77512343/140567067-82cfdb70-69e5-43f5-a0ac-e8b29255b546.png)


I need one for this filter

**Comment by ghost** [comment]
> @ZombiefiedGaming unfortunately sending links ends up in them getting blocked faster, so just join the discord. Refer to #44

the bot is dead

**Comment by MrBrastavaya** [comment]
@ZombiefiedGaming That sounds like something @QuiteAFancyEmerald may have to take a look at.

**Comment by QuiteAFancyEmerald** [comment]
Bot is up again. It has ever been so buggy
