### ISSUE TITLE
hCaptcha code updated - Corrosion needs fixed

### ISSUE THREAD

**Issue by MayMay39** [QuiteAFancyEmerald/HolyUnblockerPublic#196]
Hi, Binary-Person, the creator of Womginx stated that hCaptcha changed their code and added their Content Security Policy to a Meta Tag instead of a Header, breaking the way Womginx handled captchas. Same issue occurs with Corrosion, which is the point of this issue. This is critical because that's how you log in to Discord and various sites which restricted access by the Captcha wall. 

Anyway, yeah. I'm not a programmer so I have no idea how to fix this but the hCaptcha handling needs updated to hCaptcha's new code  or else it won't appear. Thank you.

**Comment by Maximus-Pinpoint** [comment]
For me, it appears, but it just loads after clicking the check and never finishes. Please, fix this as soon as you can.

**Comment by QuiteAFancyEmerald** [comment]
Open this same issue on the official Corrosion repository! I bet Duce would take a deep look into it :D
