### ISSUE TITLE
Discord invite link is expired

### ISSUE THREAD

**Issue by HydraXxD** [QuiteAFancyEmerald/HolyUnblockerPublic#197]
Hi, I tried to join the discord server for more info on the site and alternate links, but it seems to have expired when I clicked on it. Please fix this!

**Comment by Nebelung-Dev** [comment]
https://discord.gg/unblock is the official one (still works)

**Comment by QuiteAFancyEmerald** [comment]
Make sure you are not trying to join via a proxy!
