### ISSUE TITLE
Womginx hCaptcha issue fixed, but HU not updated

### ISSUE THREAD

**Issue by Maximus-Pinpoint** [QuiteAFancyEmerald/HolyUnblockerPublic#198]
Womginx's hCaptcha issue has been fixed, but all HU links aren't updated. Could y'all put the fixed Womginx on all existing sites? Or at least by the ones generated by the bot on the server?

**Comment by QuiteAFancyEmerald** [comment]
Uhh Womginx is fixed on all sites. They are all on the same instance. Please check out #announcments regarding the fix since cache.
