### ISSUE TITLE
Error: getaddrinfo ENOTFOUND -wuw,rmbnoz.aoo

### ISSUE THREAD

**Issue by 1333481** [QuiteAFancyEmerald/HolyUnblockerPublic#202]
When I go to certain sites e.g. roblox, it says Error: getaddrinfo ENOTFOUND -wuw,rmbnoz.aoo. I am using an instance that I hosted on repl

**Comment by s191ed** [comment]
dont use repl, use the proxies from discord as they give you proper links for the proxies. if you cant access discord ill give you one
