### ISSUE TITLE
instagram dms !!! 

### ISSUE THREAD

**Issue by insgah** [QuiteAFancyEmerald/HolyUnblockerPublic#204]
I logged into my account, I have a lottt of people in my dms, I tried to open them so i could talk to my friends while listening to music and it wouldnt load anyone, i tried all stealth and classic modes on all of the proxies (even the incognito proxy advertised in the discord, i dont know why because discord will load people so it is probably not in the script or something??

**Comment by QuiteAFancyEmerald** [comment]
This would be an issue with Corrosion sorry! Closing this due to that fact but feel free to create an issue like this at the official Corrosion repository.
