### ISSUE TITLE
holyunblocker is "offline"

### ISSUE THREAD

**Issue by s191ed** [QuiteAFancyEmerald/HolyUnblockerPublic#205]
cant do anything, tried using a different link, and it dosen't work either.
![Screenshot 2021-11-22 2 02 07 PM](https://user-images.githubusercontent.com/74692343/142927213-3c947105-9962-471f-9890-5cdb89372614.png)
.
![Screenshot 2021-11-22 2 02 23 PM](https://user-images.githubusercontent.com/74692343/142927266-8052e086-83d9-4836-8fd5-90f2a2406678.png)

**Comment by honeybun39** [comment]
yep! same with me!

**Comment by nanospearing** [comment]
The servers are down do to low funding. Please check out the discord server for more info!

**Comment by s191ed** [comment]
oh ok
