### ISSUE TITLE
Holy Unblocker is down for a bit (sorry) D:

### ISSUE THREAD

**Issue by Maximus-Pinpoint** [QuiteAFancyEmerald/HolyUnblockerPublic#207]
Whenever I try to visit a HU site, I get an Error 522: connection timed out page. Is the issue on my end or the whole unblocker?

**Comment by s191ed** [comment]
the servers are going to be offline for a couple of days, just wait until it goes back up. hypertabs, igcognito, reslillience will still work. no word until it goes back up exactly though

**Comment by Rockpods** [comment]
> Whenever I try to visit a HU site, I get an Error 522: connection timed out page. Is the issue on my end or the whole unblocker?

It is an issue with the whole unblocker. The servers are down right now. For more information visit the announcements page in the discord server. https://discord.gg/unblock

![image](https://user-images.githubusercontent.com/69652659/143088165-92050cd4-82dd-4d77-960c-c37419faa3e8.png)

**Comment by s191ed** [comment]
@Rockpods fall of holyunblocker? im joking but it could possibly happen

**Comment by eris-webserv** [comment]
Getting error 522 again... Would report on discord but I need HU for discord. D:

**Comment by eris-webserv** [comment]
Oh, no, not again!
(Infinite loading...)

**Comment by insgah** [comment]
yeah like- its down again

**Comment by belleistherose** [comment]
why is Holy-Unblocker so slow how do i make it faster

**Comment by belleistherose** [comment]
> yeah like- its down again

no shit man
