### ISSUE TITLE
All holy unblockers turned into incognito and sysya proxy doesn't work.

### ISSUE THREAD

**Issue by vackyton** [QuiteAFancyEmerald/HolyUnblockerPublic#209]
It says 401 unauthorised.

**Comment by JH-NYY** [comment]
the games don't work either

**Comment by CheezeKake77** [comment]
I have the same issue

**Comment by QuiteAFancyEmerald** [comment]
#207 

Also you are not setting up external proxies correctly. Make sure you are using an official Holy Unblocker site also since I removed SysYA proxy ages ago.

**Comment by vackyton** [comment]
@QuiteAFancyEmerald  i mean the incognito uses sysya proxy right? if you look above it says my holy unblocker is turned into incognito, degreefinder.cf is the site
