### ISSUE TITLE
Can't use it

### ISSUE THREAD

**Issue by AllenHeyMan** [QuiteAFancyEmerald/HolyUnblockerPublic#211]
Candlewording.xyz says "401, Unauthorized!" so i don't know what to do.

**Comment by nevr13** [comment]
don't post links that were given to you by the bot, or anyone else, as this hurts Holy Unblocker.

**Comment by QuiteAFancyEmerald** [comment]
You need to be accessing whatever site you are trying to access directly from HU :D
