### ISSUE TITLE
VibeOs emulator not working

### ISSUE THREAD

**Issue by ToadSaidHi** [QuiteAFancyEmerald/HolyUnblockerPublic#225]
The vibe os emulator's search does not work. Bing and Duck Duck go are blocked, and the main search does not work.

**Comment by s191ed** [comment]
Its archived, and it seems like its never going to be updated again. Suggest using another OS as a replacement.

**Comment by ToadSaidHi** [comment]
Well, I mean, I would be fine with any os, like a version of Linux that someone can run. I would just like a working computer emulator

**Comment by Nebelung-Dev** [comment]
vibeOS has been discontinued. you can view my version here https://vibeos.nebelung.repl.co/
