### ISSUE TITLE
RECaptcha, 2Captcha, HCaptcha won't show.

### ISSUE THREAD

**Issue by bestgamerytreal** [QuiteAFancyEmerald/HolyUnblockerPublic#226]
RECaptcha, 2Captcha, HCaptcha won't work.
Can this be fixed?
IMAGE
[LINK](https://ibb.co/mc7qsFG)

**Comment by s191ed** [comment]
use womginx because its the only proxy i know that supports it, also use the QR code if you are trying to get into discord

**Comment by QuiteAFancyEmerald** [comment]
Corrosion issue sadly and duplicate. Being worked on tho by Duce! :D
