### ISSUE TITLE
Holy Unblocker is down... again.

### ISSUE THREAD

**Issue by s191ed** [QuiteAFancyEmerald/HolyUnblockerPublic#228]
Discord dosent work, the websites are super slow, and nothing seems to be working properly. 
![image](https://user-images.githubusercontent.com/74692343/147276519-60fb61eb-d401-4c37-9055-51860bd5155d.png)

![image](https://user-images.githubusercontent.com/74692343/147277329-60c76056-d800-48e3-a69c-14ee966710d3.png)

**Comment by CheezeKake77** [comment]
I am experiencing the same exact issue, the sites are slow to load, and when they do I get a 522 error

**Comment by insgah** [comment]
same lol

**Comment by Nebelung-Dev** [comment]
It will be down for a while
