### ISSUE TITLE
webretro update

### ISSUE THREAD

**Issue by Maximus-Pinpoint** [QuiteAFancyEmerald/HolyUnblockerPublic#229]
When I open a game, it shows a start button and this:
```
New webretro version available: v6.4. Features:
- ability to change keybinds
- take and download screenshots
- recover saves and states from lost or renamed roms
- shaders added to bundle
- disable webcam usage for gameboy
The site owner(s) can apply the update.
```

Could y'all apply the update, since switching keybinds would be really nice? Thanks

**Comment by nevr13** [comment]
you can host your own on https://replit.com from https://github.com/BinBashBanana/webretro

**Comment by QuiteAFancyEmerald** [comment]
Updated has been applied (has been for awhile lol)
