### ISSUE TITLE
N64 Emulator

### ISSUE THREAD

**Issue by MRMRMEATS** [QuiteAFancyEmerald/HolyUnblockerPublic#234]
Hello there. I've noticed that the N64 emulator has been down for a while now. I was wondering if that could be fixed or maybe could you just add Zelda Ocarina of Time and/or Majoras Mask to the HTML5 games list? That would make my day very much.

**Comment by Christian32307** [comment]
The N64 Emulator has major visual bugs, and crashes often. 
It might still be in the files but I'm not sure.

**Comment by MRMRMEATS** [comment]
oh ok. even if the n64 emulator doesnt work could I suggest two more n64 games for the html5 section?

**Comment by Christian32307** [comment]
The Mario 64 port was done through a decompilation of the game
and recompiled for web with emscripten

**Comment by MRMRMEATS** [comment]
cant the same thing be done for ocarina of time and majoras mask?

**Comment by BigFatJoeMama** [comment]
EmulatorJS is better for n64 emulation.
