### ISSUE TITLE
This literally isn't even up-to-date with the Holy Unblocker website.

### ISSUE THREAD

**Issue by NotSorena** [QuiteAFancyEmerald/HolyUnblockerPublic#235]
When you put it on Heroku or Glitch it doesn't have PyDodgeB, the updated version of Corrosion (new corrosion works with https://now.gg/play/roblox-corporation/5349/roblox on the official holy unblocker site) and webosu!

What is this?

**Comment by QuiteAFancyEmerald** [comment]
PyDodge has been removed for a long awhile but this repository is only the
public version of Holy Unblocker; hence why some changes are private or not
public yet.

**Comment by 20018187-ux** [comment]
how do u even download Roblox???

**Comment by 20018187-ux** [comment]
but the holy unblocker is fire like fuckin crazy
