### ISSUE TITLE
Holy Unblocker is down or domain "expired" issues

### ISSUE THREAD

**Issue by SubduedCyns** [QuiteAFancyEmerald/HolyUnblockerPublic#248]

**Comment by Nebelung-Dev** [comment]
From this discord: `The main DNS record for HU expired.... more and more problems sorry. Solution already exists but now I need to update around 140+ domains manually on CF sorry.`

**Comment by s191ed** [comment]
> From this discord: `The main DNS record for HU expired.... more and more problems sorry. Solution already exists but now I need to update around 140+ domains manually on CF sorry.`
God damn LOL

**Comment by eris-webserv** [comment]
delete the image, you're leaking a proxy link

**Comment by hellowpplz** [comment]
> delete the image, you're leaking a proxy link

And that's a bad thing how?

**Comment by kaeyagirl** [comment]
> 

do u know any other proxies that works? bc herokuapp not working no more.

**Comment by hellowpplz** [comment]
Uhm, unblocker wise?
________________________________
From: took him 2 dubai . ***@***.***>
Sent: Friday, January 21, 2022 12:33 AM
To: titaniumnetwork-dev/Holy-Unblocker ***@***.***>
Cc: Student - Barron, Kayden E. ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [titaniumnetwork-dev/Holy-Unblocker] Holy Unblocker is down or domain "expired" issues (Issue #248)


do u know any other proxies that works? bc herokuapp not working no more.

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftitaniumnetwork-dev%2FHoly-Unblocker%2Fissues%2F248%23issuecomment-1018196026&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C3b3d4ef5fea146f49a5308d9dc9fa06b%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637783400433729562%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mBp5d6rOfWn55RVdMRyDfJWXrvYYxRSIarKXZf4wCbg%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWSVTEDXC4OIN7MDJWCNZI3UXDV4NANCNFSM5MDKM5GA&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C3b3d4ef5fea146f49a5308d9dc9fa06b%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637783400433729562%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DsCESxX97WBODMC%2BZlpCC%2Fsttdph2c8Vzlq0vfvzNnc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C3b3d4ef5fea146f49a5308d9dc9fa06b%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637783400433886180%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QNf8eXXPJtoD7TRNZ1ig48Id6bvSxqDR4Jm5aQqR2zo%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C3b3d4ef5fea146f49a5308d9dc9fa06b%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637783400433886180%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bHdnfn2YeSIcChfHLR6uouSMqacbft39eMhACfOY88k%3D&reserved=0>.

**Comment by hellowpplz** [comment]
jk ctaetcsh.lgbt It's hypertabs which sometimes slows down but's pretty consistent recently
________________________________
From: took him 2 dubai . ***@***.***>
Sent: Friday, January 21, 2022 12:33 AM
To: titaniumnetwork-dev/Holy-Unblocker ***@***.***>
Cc: Student - Barron, Kayden E. ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [titaniumnetwork-dev/Holy-Unblocker] Holy Unblocker is down or domain "expired" issues (Issue #248)


do u know any other proxies that works? bc herokuapp not working no more.

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftitaniumnetwork-dev%2FHoly-Unblocker%2Fissues%2F248%23issuecomment-1018196026&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C3b3d4ef5fea146f49a5308d9dc9fa06b%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637783400433729562%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mBp5d6rOfWn55RVdMRyDfJWXrvYYxRSIarKXZf4wCbg%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWSVTEDXC4OIN7MDJWCNZI3UXDV4NANCNFSM5MDKM5GA&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C3b3d4ef5fea146f49a5308d9dc9fa06b%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637783400433729562%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DsCESxX97WBODMC%2BZlpCC%2Fsttdph2c8Vzlq0vfvzNnc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C3b3d4ef5fea146f49a5308d9dc9fa06b%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637783400433886180%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QNf8eXXPJtoD7TRNZ1ig48Id6bvSxqDR4Jm5aQqR2zo%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C3b3d4ef5fea146f49a5308d9dc9fa06b%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637783400433886180%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bHdnfn2YeSIcChfHLR6uouSMqacbft39eMhACfOY88k%3D&reserved=0>.

**Comment by kaeyagirl** [comment]
uhh, i tried it but when i go on discord. it dont ask me for de verify thing . so it wont let me go on discord. and its so slow

**Comment by kaeyagirl** [comment]
@hellowpplz

**Comment by kaeyagirl** [comment]
![Uploading Screenshot 2022-01-21 8.58.08 AM.png…]()

**Comment by eris-webserv** [comment]
> > delete the image, you're leaking a proxy link
> 
> And that's a bad thing how?

Leaking proxy links is against TN rules. Plus, I USE THAT LINK!

**Comment by hellowpplz** [comment]
I did that multiple times but okay. (Don't ban meeeeeeeeeeee :p)
________________________________
From: Eris ***@***.***>
Sent: Friday, January 21, 2022 3:03 PM
To: titaniumnetwork-dev/Holy-Unblocker ***@***.***>
Cc: Student - Barron, Kayden E. ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [titaniumnetwork-dev/Holy-Unblocker] Holy Unblocker is down or domain "expired" issues (Issue #248)


delete the image, you're leaking a proxy link

And that's a bad thing how?

Leaking proxy links is against TN rules. Plus, I USE THAT LINK!

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftitaniumnetwork-dev%2FHoly-Unblocker%2Fissues%2F248%23issuecomment-1018820034&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7Cda92bcc259d5419626db08d9dd190c84%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637783921922117317%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3uuo172Jvp6BiU1Y75hIT0frOG62UvvidRs55jFYiOg%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWSVTEADMVH56L74IFQTEMTUXG3X3ANCNFSM5MDKM5GA&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7Cda92bcc259d5419626db08d9dd190c84%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637783921922117317%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6L9t5wDeRSWTx%2FnWO4VdKYhpE6hGrAezeVEhvcoyZTU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7Cda92bcc259d5419626db08d9dd190c84%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637783921922117317%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Q0XswBRoU3OREbgMA7YAZJL9wiKdW2oCwX%2BQfQZLMFg%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7Cda92bcc259d5419626db08d9dd190c84%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637783921922117317%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EdzvYgornfX1M34dSfD0ln%2BuIcAFg%2FQ14lhReP%2FXOwk%3D&reserved=0>.

**Comment by QuiteAFancyEmerald** [comment]
back up
