### ISSUE TITLE
The source code violates Heroku's Salesforce Acceptable Use and External-Facing Services Policy.

### ISSUE THREAD

**Issue by Yeetdababy97** [QuiteAFancyEmerald/HolyUnblockerPublic#250]
i tried to deploy the app in heroku and a message popped up saying "We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy."

**Comment by QuiteAFancyEmerald** [comment]
Oh? I'll look into this. Although it's possible that I can't really do anything about it sadly.

EDIT: Check out https://railway.app. Deploy button is linked on the README. **Railway** seems to be a much better alternative to Heroku.

**Comment by Rockpods** [comment]
~~I am too lazy to test but does forking the repo and changing the run with heroku link to your own repo fix this?~~
Edit: I tested it and it works

**Comment by kaeyagirl** [comment]
> ~I am too lazy to test but does forking the repo and changing the run with heroku link to your own repo fix this?~ Edit: I tested it and it works

screenshot? it dont work for me

**Comment by Rockpods** [comment]
> > ~I am too lazy to test but does forking the repo and changing the run with heroku link to your own repo fix this?~ Edit: I tested it and it works
> 
> screenshot? it dont work for me

It might have been that I had the old HU forked back when it was named HolyUnblockerPublic. I will test again and add a tutorial today or tomorrow.

**Comment by kaeyagirl** [comment]
k

**Comment by Rockpods** [comment]
> k

Sorry for being late but here are the instructions.

Prerequisites:
Have a [Github](https://github.com) and [Heroku](https://id.heroku.com/login) account.

Tutorial:
1. Fork the [Holy Unblocker GitHub](https://github.com/titaniumnetwork-dev/Holy-Unblocker)
![image](https://user-images.githubusercontent.com/69652659/151097766-a8456d98-b857-41bd-85fd-064b1f8feffc.png)
2. Copy this link https://heroku.com/deploy?template=https://github.com/QuiteAFancyEmerald/Holy-Unblocker
3. Now change "QuiteAFancyEmerald" to your username.
4. Then you can just go to the link.
5. If this does not work and you have had Holy Unblocker forked for a while try steps 2 through 4 with https://heroku.com/deploy?template=https://github.com/QuiteAFancyEmerald/HolyUnblockerPublic instead.

**Comment by QuiteAFancyEmerald** [comment]
ty!

**Comment by Lhinger** [comment]
i got banned in heroku for it :/

**Comment by QuiteAFancyEmerald** [comment]
Heroku is no longer supported.
