### ISSUE TITLE
Websites expired, cant use anything

### ISSUE THREAD

**Issue by s191ed** [QuiteAFancyEmerald/HolyUnblockerPublic#252]
![image](https://user-images.githubusercontent.com/74692343/149981698-fbae7243-b43c-4d24-a939-eae2d2eaf96c.png)
![image](https://user-images.githubusercontent.com/74692343/149981736-b03b4d67-0edf-4349-bb2b-3fe1a2944072.png)

**Comment by SubduedCyns** [comment]
delete the image, you're leaking proxy links

**Comment by QuiteAFancyEmerald** [comment]
#248

**Comment by QuiteAFancyEmerald** [comment]
yea yea I messed some stuff up
