### ISSUE TITLE
new proxy web but not sure if it works.. 

### ISSUE THREAD

**Issue by kaeyagirl** [QuiteAFancyEmerald/HolyUnblockerPublic#256]
it looks like holy unblocker website , but idk if thats the new one. i just found it

**Comment by Rockpods** [comment]
![image](https://user-images.githubusercontent.com/69652659/150614186-ac78bdce-db68-4b56-a9cf-d22567d79120.png)

**Comment by SubduedCyns** [comment]
It doesn't work sadly, the cloudfront just "Blocks" it? IDK

**Comment by kaeyagirl** [comment]
oh. i see,

**Comment by QuiteAFancyEmerald** [comment]
Um what? Check out my response in your most recent issue :D 

(I think you are asking the same thing idk)
