### ISSUE TITLE
sysya not working

### ISSUE THREAD

**Issue by easella** [QuiteAFancyEmerald/HolyUnblockerPublic#26]
![image](https://user-images.githubusercontent.com/74786054/110248393-d26d2400-7f3e-11eb-96c9-4339a4cadafe.png)

**Comment by QuiteAFancyEmerald** [comment]
Um, you don't have any external proxies setup. This repository for Holy Unblocker only has Alloy locally. Please read the README for more information.

You've already opened up issues similar to this, please read over my responses. 
#24
