### ISSUE TITLE
flexibleedu.gq wont work

### ISSUE THREAD

**Issue by JoeyMeepLand** [QuiteAFancyEmerald/HolyUnblockerPublic#260]
flexibleedu.gq wont work can you fix it. it was a website that displayed holyunblocker but it shows IT

**Comment by Nebelung-Dev** [comment]
HU is back up now

**Comment by kaeyagirl** [comment]
> HU is back up now

oh, it doesnt work 4 me, how do i go on discord LMAO

**Comment by QuiteAFancyEmerald** [comment]
You can either use Corrosion or Womginx for Discord :D 
`https://discord.com/app` or `https://discord.com/login`
