### ISSUE TITLE
Xbox OG or Xbox 360 emulator

### ISSUE THREAD

**Issue by MuricaFrog** [QuiteAFancyEmerald/HolyUnblockerPublic#262]
I was thinking maybe you guys could add a Xbox  emulator of some sorts, I dont know which but It would be nice to see it if you guys can do it.If you can, pls add halo 1 or (preferably 2) onto the page. I totally get it if you cant.
Thanks, hope to see it!
(Ps also could you fix the N64 Emulator, I know thats probably said a lot, but just wanted to mention it)

**Comment by polybiusproxy** [comment]
there isn't any xbox emulator for html5
there is an xbox og and xbox 360 emulator but those are for pc only

**Comment by Nebelung-Dev** [comment]
If you can find a open source one, put it here

**Comment by MRMRMEATS** [comment]
@MuricaFrog lol. I've been trying to get them to fix the N64 emulator as well. Its been broken for months and I was hoping it would fix. good luck on your request too. An og XBox emulator would be sweet.

**Comment by polybiusproxy** [comment]
> If you can find a open source one, put it here

https://github.com/xenia-project/xenia -- xbox 360 emulator
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded -- og xbox emulator

**Comment by QuiteAFancyEmerald** [comment]
I'm sorry I'm not sure if this is possible currently. Unless if something with libretro exists nothing much can be done for a web version of this :((
