### ISSUE TITLE
What happened to palladium? It used to be on this website, but its not anymore. 

### ISSUE THREAD

**Issue by Imatschoolandeverythingisblockedplshelp** [QuiteAFancyEmerald/HolyUnblockerPublic#263]
(https://user-images.githubusercontent.com/79165570/151165132-bef039f3-871c-427c-9b9d-a624cbfa653b.png)

**Comment by Imatschoolandeverythingisblockedplshelp** [comment]
Also, hCaptcha is broken on womginx.
(https://user-images.githubusercontent.com/79165570/151170359-8e224988-8b57-4343-b43f-ce713a862df2.png)

**Comment by kaeyagirl** [comment]
what proxy web is that?, can u send the link?

**Comment by Imatschoolandeverythingisblockedplshelp** [comment]
> what proxy web is that?, can u send the link?
You're not allowed to leak proxy websites I believe, so is there any way I can send you the link privately?

**Comment by kaeyagirl** [comment]
UHH i think so .

**Comment by Imatschoolandeverythingisblockedplshelp** [comment]
> UHH i think so .

Can you tell me how so I can send the link?

**Comment by kaeyagirl** [comment]
how abt u write it on ur bio? or ur status LMAOOO bc im in  school and idk how to dm u or give u any other socials .

**Comment by Imatschoolandeverythingisblockedplshelp** [comment]
Done.

**Comment by kaeyagirl** [comment]
![Screenshot 2022-01-26 8 43 56 AM](https://user-images.githubusercontent.com/97773770/151184448-2ecf84e0-916c-47dc-a149-e26a19718931.png)

**Comment by Imatschoolandeverythingisblockedplshelp** [comment]
> ![Screenshot 2022-01-26 8 43 56 AM](https://user-images.githubusercontent.com/97773770/151184448-2ecf84e0-916c-47dc-a149-e26a19718931.png)

What the heck?

**Comment by kaeyagirl** [comment]
its not working

**Comment by Imatschoolandeverythingisblockedplshelp** [comment]
I don't know why but I just need palladium back on this website so I can actually use discord.

**Comment by kaeyagirl** [comment]
how did it work 4 u?

**Comment by Imatschoolandeverythingisblockedplshelp** [comment]
I don't know, it just always works

**Comment by kaeyagirl** [comment]
what did u type on google search?😭

**Comment by Imatschoolandeverythingisblockedplshelp** [comment]
> what did u type on google search?😭

I juts typed in the link and the website works. I just asked for someone to help with palladium, and you can't help me.

**Comment by kaeyagirl** [comment]
how can i help u? if the web doesnt work.

**Comment by Imatschoolandeverythingisblockedplshelp** [comment]
> how can i help u? if the web doesnt work.

You can't, unfortunately.

**Comment by kaeyagirl** [comment]
okay ill try to help u but can you screenshot the whole website ? w the link?

**Comment by Imatschoolandeverythingisblockedplshelp** [comment]
> okay ill try to help u but can you screenshot the whole website ? w the link?

No, I don't want to get in any sort of issues due to posting links publicly

**Comment by QuiteAFancyEmerald** [comment]
It's no longer being updated sadly and will be replaced with something soon. Due to its lack of functionality and slow speeds I removed it.
