### ISSUE TITLE
It’s back

### ISSUE THREAD

**Issue by RussianPolice** [QuiteAFancyEmerald/HolyUnblockerPublic#264]
But it doesn’t work, nothing works

**Comment by kaeyagirl** [comment]
how is it back?

**Comment by RussianPolice** [comment]
![3763417D-A674-485E-8BC8-352C680A95AC](https://user-images.githubusercontent.com/95244254/151399453-99c8f62d-253a-4612-a0c9-1e3823fd395a.jpeg)

**Comment by kaeyagirl** [comment]
oh , can u put the link in ur bio pls? ill see if i can make it work . but idk whats the web called.

**Comment by RussianPolice** [comment]
Sure

**Comment by kaeyagirl** [comment]
u done?

**Comment by RussianPolice** [comment]
Yeah sorry I put it in the wrong spot

**Comment by kaeyagirl** [comment]
let me know when ur done.

**Comment by RussianPolice** [comment]
I’m done now

**Comment by kaeyagirl** [comment]
no it doesnt work 4 me. idk why.

**Comment by kaeyagirl** [comment]
do u know any other web proxies?

**Comment by QuiteAFancyEmerald** [comment]
Holy Unblocker should be back up now! If you need more HU sites join the TN Discord and type out "%proxy hu". The bot there will DM you another site :D 

And what site isn't working for you on HU. Better yet, what HU site are you on? This can be an exception where you publicly post the link.

**Comment by RussianPolice** [comment]
I’m using mathbot.xyz and when I try to use anything on that holy unblocker link it comes up as a blank white page
