### ISSUE TITLE
Only Corrosion Classic works (using Glitch)

### ISSUE THREAD

**Issue by ToasterPanic** [QuiteAFancyEmerald/HolyUnblockerPublic#265]
Hosting a site on Glitch, Womginx doesn't work in any way and Corrosion on Stealth mode doesn't work either. No other hosting providers are available because they're all blocked, and I don't really know what options I have at this point to get Stealth working.

Womginx returns the "Well, you found a glitch" screen on Classic mode and Stealth mode.
Corrosion on Stealth mode gives me a blank screen.

If it helps, the link is https://quiet-handy-period.glitch.me.

**Comment by QuiteAFancyEmerald** [comment]
Any type of free hosting provider is pretty whacky. But regarding the other proxies on HU blanking out that would be because you don't have any other external proxies setup. Only Corrosion is hosted locally with the public source of HU (check out the README for more info).
