### ISSUE TITLE
Question about pokemon emerald

### ISSUE THREAD

**Issue by MRMRMEATS** [QuiteAFancyEmerald/HolyUnblockerPublic#266]
Hai, Was just wondering if the super rare chance of getting a shiny starter was still possible with this emulator? I know of some emulator sites that don't have that ability and was just wondering if this was the same?

**Comment by RussianPolice** [comment]
There is a great emulator want me to link it? It has games like contra sonic 2 3 and sonic chaos gbc emulators nes emulators and more.

**Comment by SubduedCyns** [comment]
Yes please

**Comment by RussianPolice** [comment]
It’s skitty. xyz

**Comment by SubduedCyns** [comment]
Sad, its blocked :(

**Comment by SubduedCyns** [comment]
> Hai, Was just wondering if the super rare chance of getting a shiny starter was still possible with this emulator? I know of some emulator sites that don't have that ability and was just wondering if this was the same?

Yeah, I've gotten shinies before on this. This is the RetroArch emulator, it acts as a normal emulator with a few tweaks.

**Comment by SubduedCyns** [comment]
The chance of getting a shiny in pokemon emerald is 1 in 8192 encounters. This is NOT, however, guaranteed, as after 8192 encounters you still have the same exact chance as before

**Comment by MRMRMEATS** [comment]
mkay thnx for the info. :)

**Comment by MRMRMEATS** [comment]
@Cha0t1cDX speaking of retroarch, I can't ever get the N64 emulator to work. Is there something wrong with it? Or do you possibly know of a working browser based N64 emulator?

**Comment by QuiteAFancyEmerald** [comment]
You might need to find a ROM for that or a cheat (cheats are supported)? So yes it should be possible lol

Not exactly sure where you would find something like that tho~
