### ISSUE TITLE
How do you fix the source code security  thing about sales force.com

### ISSUE THREAD

**Issue by SonicFan019** [QuiteAFancyEmerald/HolyUnblockerPublic#267]
![D53D17DB-B243-4769-96CC-8D764ABAB4C4](https://user-images.githubusercontent.com/93418630/151652947-2cca70d6-b3ba-4ff0-ab5c-852cc19a480d.jpeg)
I need help __

Also my account name is Caleb Gonzalez all lowercase

**Comment by QuiteAFancyEmerald** [comment]
Ah Heroku moments. Try looking into making your own fork and changing app.json up a bit for your purposes. Otherwise nothing much you can do except change free hosting providers.

(Look into Oracle VM) :D
