### ISSUE TITLE
Goguardian 

### ISSUE THREAD

**Issue by GoogleWasAllMyIdea** [QuiteAFancyEmerald/HolyUnblockerPublic#268]
It blocked the website I was using """" and I can't use discord it is also blocked so what can I do to fix this? Maybe is there another link? Because when I used to use the other one websites still would get blocked sometimes.

Here's the proof that it is blocked:

"""

**Comment by nevr13** [comment]
Do not put holy unblocker links in issues, please. If the link is blocked, don't post these types of issues. You can join Titanium Network on Discord (https://discord.gg.unblock) for more links. You can also self-host your own proxy. As a beginner, Holy Unblocker doesn't have a user-friendly setup. I recommend setting up Womginx (https://github.com/binary-person/womginx) on https://replit.com. Go ahead and make an account on https://replit.com, and then go back to Womginx,(https://github.com/binary-person/womginx) then click "Run on repl.it in the readme.md of the document (the long text document on the Womginx source code page. Then, once you set up a REPL with Womginx on it,  click the giant big green button on the page that says "Run". Then, wait for it to complete. Now you have a proxy that can use discord, and some other sites on. you can setup different proxies for more support. Here are some of them:

Incognito (https://github.com/titaniumnetworkdev/incognito)
Palladium (https://github.com/LudicrousDevelopment/Palladium)
Corrosion [not a user friendly setup]

**Comment by GoogleWasAllMyIdea** [comment]
Replit is blocked so is the unblocked discord I can't use this because of it. Thanks anyways.
