### ISSUE TITLE
The Discord link on the website wont work.

### ISSUE THREAD

**Issue by Breadza** [QuiteAFancyEmerald/HolyUnblockerPublic#273]

**Comment by luphoria** [comment]
please explain?

**Comment by ThatOneKidAtSchool** [comment]
> please explain?

It brings you either to a 404 if you use proxy list and a blank white page using discord links

**Comment by MRMRMEATS** [comment]
It works every now and then but its doing the weird "Somethings going on here. Verify your account" thing. and when I verified it, it decided to not work and makes me refresh the page an infinite number of times. So its just an overall bug. It worked fine for a few days after the all the sites went down and then they had to be manually rebooted. But after I tried signing in again it just won't work.

**Comment by MRMRMEATS** [comment]
But the site has some bugs too, like how Womingx wont ever load. And how some video sites wont play the videos with Corrosion

**Comment by luphoria** [comment]
> > please explain?
> 
> It brings you either to a 404 if you use proxy list and a blank white page using discord links
> 

I cant reproduce this

**Comment by ThatOneKidAtSchool** [comment]
> > > please explain?
> > 
> > 
> > It brings you either to a 404 if you use proxy list and a blank white page using discord links
> 
> I cant reproduce this

Huh?, so it works for you

**Comment by luphoria** [comment]
> > > > please explain?
> > > 
> > > 
> > > It brings you either to a 404 if you use proxy list and a blank white page using discord links
> > 
> > I cant reproduce this
> 
> Huh?, so it works for you

Yes

**Comment by QuiteAFancyEmerald** [comment]
Hey,
Can you provide more information about this issue such as steps to reproduce and screenshots? Make sure you are not using Palladium by the way. Also even more important: are you trying to host yourself or using the official websites?

**Comment by MRMRMEATS** [comment]
@QuiteAFancyEmerald I am using the official sites. And I know from personal experience that palladium doesnt work. here is a short vid of what happens. No matter how many times I verify the account it doesnt work

https://user-images.githubusercontent.com/96854645/152619722-d680cefa-6096-43b0-b3d7-75035e1d9fb8.mp4

.

**Comment by kaeyagirl** [comment]
oh thats what happened to me, is it the phone number or the email thing?

**Comment by kaeyagirl** [comment]
@MRMRMEATS

**Comment by hellowpplz** [comment]
> 

Just gonna ask, How many people use chromebooks? 

Schools are addicted and it's annoying me bit by bit. I can't use inspect tool so there's no me helping you.

**Comment by hellowpplz** [comment]
> @MRMRMEATS

For me it's phone number
Edit: It did make me do email once but then went to phone number, which is the problem causer.

**Comment by ToasterWaffl** [comment]
This has been patched by binary person themselves we just have to wait for womgnix tp update

**Comment by Altablekez** [comment]
> @QuiteAFancyEmerald I am using the official sites. And I know from personal experience that palladium doesnt work. here is a short vid of what happens. No matter how many times I verify the account it doesnt work
> 
>  Screen.recording.2022-02-04.4.12.17.PM.mp4 
> .

bro r u dum, get a phone and verify. Discord does this because  it thinks someone is tryin to acces ur account. So it needs to verify a bot isnt doing this and asks u to use a phone to verify ur human. They dont use captacha cuz its easily bypassed by computers. idk ask ur mom 4 her phone or smth
