### ISSUE TITLE
Alt Urls?

### ISSUE THREAD

**Issue by Phoenix3214** [QuiteAFancyEmerald/HolyUnblockerPublic#274]
Hello, I am a frequent user of Holy-Unblocker but just recently, my school has blocked your website. Is there another way to access Holy Unblocker when the main url is blocked??? Maybe consider making alt urls?? 

Thanks, 
Phoenix3214

**Comment by MRMRMEATS** [comment]
@Phoenix3214 according to the "laws" of The HU we can't "legally" post links here in the github. If you don't have any way of getting to the discord then you might be S.O.L but you can send me an email. If you need alt links I'll find a way to dm you. I've collected a bunch over the past few months.

**Comment by QuiteAFancyEmerald** [comment]
@Phoenix3214 Check out #44 lol

Holy Unblocker has always had mirror links which are restocked monthly in the TN discord
