### ISSUE TITLE
Y'all down again?

### ISSUE THREAD

**Issue by MRMRMEATS** [QuiteAFancyEmerald/HolyUnblockerPublic#278]
This is like the 5th time this year. and the year just started? is it down constantly cuz of updates or is there something legitimately wrong with the HU?

**Comment by MRMRMEATS** [comment]
Also what happened to Alloy and Palladium? They just vanished and were good sources for stuff

**Comment by easella** [comment]
i dont know

**Comment by easella** [comment]
yeah why were they taken down. put back node unblocked and pydodge and via unblocker

**Comment by s191ed** [comment]
> yeah why were they taken down. put back node unblocked and pydodge and via unblocker

eh, pydodge is ok but via and node are trash now. #beingalloyback
