### ISSUE TITLE
Code against Glitch ToS

### ISSUE THREAD

**Issue by cerebralshape** [QuiteAFancyEmerald/HolyUnblockerPublic#279]
Similar to heroku blocking HU (#250 ) glitch also stopped supporting HU. Even if the repository has the same code but different repo name, it still detects that it is similar to this. 

Fixes/alternatives?

**Comment by s191ed** [comment]
use replit, its our only hope. ive created a womginx instance in replit right here: https://www.womginx.gq

**Comment by cerebralshape** [comment]
i'll try to use vercel, will update if works.

**Comment by QuiteAFancyEmerald** [comment]
Read my updated comment #250
