### ISSUE TITLE
Support for NDS Emulator?

### ISSUE THREAD

**Issue by cerebralshape** [QuiteAFancyEmerald/HolyUnblockerPublic#280]
I've searched for an NDS retroarch core and found that there is a core for Citra however there is no way to get this core (that i have found) other than downloading it with the desktop app which I cannot do. I know this is possible with sites like [emulatorgames.online](emulatorgames.online) but these aren't open source. 
Can someone add support for NDS? I will keep searching for cores.

**Comment by MRMRMEATS** [comment]
Hey, I've seen a similar post to this and Emerald already said he doesn't know if this is even possible atm. Unless your new info helps I don't think this can be done. Sorry for the inconvenience. :)

**Comment by QuiteAFancyEmerald** [comment]
WIP and duplicate
