### ISSUE TITLE
Ah yes this is greay

### ISSUE THREAD

**Issue by hellowpplz** [QuiteAFancyEmerald/HolyUnblockerPublic#281]
Hyper tabs was doing GREAT over the weekend. But guess what we are back to...

![image](https://user-images.githubusercontent.com/94722448/152854624-5d334a4c-46f6-4306-bb71-ce1ec1038ab4.png)

Only reason I cut it off is so I didn't link the url of which was shown.

*Edit: The host, (url which can not be shown) was the error stopping it.

**Comment by MRMRMEATS** [comment]
Just expect this from hyper tabs. They kinda suck and they're really slow. And not to mention constantly down. Just use the HU. Its also down constantly but not nearly as slow as hyper tabs. Not by a long shot.

**Comment by hellowpplz** [comment]
Well again, over the weekend I was literally running anything imaginable on hypertabs that would freeze hu. So at times, that statement is debatable.
________________________________
From: MRMRMEATS ***@***.***>
Sent: Monday, February 7, 2022 6:13 PM
To: titaniumnetwork-dev/Holy-Unblocker ***@***.***>
Cc: Student - Barron, Kayden E. ***@***.***>; Author ***@***.***>
Subject: [External] Re: [titaniumnetwork-dev/Holy-Unblocker] Ah yes this is greay (Issue #281)


Just expect this from hyper tabs. They kinda suck and they're really slow. And not to mention constantly down. Just use the HU. Its also down constantly but not nearly as slow as hyper tabs. Not by a long shot.

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftitaniumnetwork-dev%2FHoly-Unblocker%2Fissues%2F281%23issuecomment-1032030702&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C7c0430304f234dd1a7ce08d9ea8f75d2%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637798724149228170%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8j4KR2gPI34xLBJLPTRQ8MaHI5MjEph%2BJ0otebFcdFk%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWSVTEGHLZIZCPPZB2OVHJLU2BGZXANCNFSM5NYJ7BPA&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C7c0430304f234dd1a7ce08d9ea8f75d2%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637798724149228170%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HN6%2Fsn36UStP%2F6fJFIjaJsH0we%2FjsXxX41sJBeaSt7Y%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C7c0430304f234dd1a7ce08d9ea8f75d2%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637798724149228170%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SMObU3gS0gzQyPayhXqQUbbe5zkP2jPK0L%2F0uMQG9NU%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C7c0430304f234dd1a7ce08d9ea8f75d2%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637798724149384398%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jaSF2BiQZqQvtL2VdsizlE%2B2%2F%2FF7XBOMhiiGHRaQNak%3D&reserved=0>.

**Comment by MRMRMEATS** [comment]
@hellowpplz From my experience hyper tabs have been either slow or down. Maybe I'm always catching it at the wrong time? lol

**Comment by hellowpplz** [comment]
Prob or it's down in certain locations only
________________________________
From: MRMRMEATS ***@***.***>
Sent: Tuesday, February 8, 2022 11:07 AM
To: titaniumnetwork-dev/Holy-Unblocker ***@***.***>
Cc: Student - Barron, Kayden E. ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [titaniumnetwork-dev/Holy-Unblocker] Ah yes this is greay (Issue #281)


@hellowpplz<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhellowpplz&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C80fa226618454515bf9b08d9eb1d261f%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637799332732347612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kU8XO0xALMde9myMzY3Ywaj%2Fborav2AAhrFogVFphxQ%3D&reserved=0> From my experience hyper tabs have been either slow or down. Maybe I'm always catching it at the wrong time? lol

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftitaniumnetwork-dev%2FHoly-Unblocker%2Fissues%2F281%23issuecomment-1032784915&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C80fa226618454515bf9b08d9eb1d261f%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637799332732347612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yXk7IA4DZj66HIpqWV7oVLE0e3yB1CRK6Q5ZfR5btSs%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWSVTEDBS3NJ2PHASPUW5H3U2E5VHANCNFSM5NYJ7BPA&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C80fa226618454515bf9b08d9eb1d261f%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637799332732347612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jLBhQdzuvp4KCzXWyswl8uK5tYCYk3Q1U1G%2FjLkWE%2FQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C80fa226618454515bf9b08d9eb1d261f%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637799332732347612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PW7tqDx5TGUBAqHZFhGMoJ4ujm2GGlEauyNVHqtTZTg%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C80fa226618454515bf9b08d9eb1d261f%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637799332732347612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZuOyEJoTLjmiOGd1vKDSv%2Bj5NRHRCcufZ3AS97EJr0U%3D&reserved=0>.

**Comment by hellowpplz** [comment]
And in others it's up
________________________________
From: MRMRMEATS ***@***.***>
Sent: Tuesday, February 8, 2022 11:07 AM
To: titaniumnetwork-dev/Holy-Unblocker ***@***.***>
Cc: Student - Barron, Kayden E. ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [titaniumnetwork-dev/Holy-Unblocker] Ah yes this is greay (Issue #281)


@hellowpplz<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhellowpplz&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C80fa226618454515bf9b08d9eb1d261f%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637799332732347612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kU8XO0xALMde9myMzY3Ywaj%2Fborav2AAhrFogVFphxQ%3D&reserved=0> From my experience hyper tabs have been either slow or down. Maybe I'm always catching it at the wrong time? lol

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftitaniumnetwork-dev%2FHoly-Unblocker%2Fissues%2F281%23issuecomment-1032784915&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C80fa226618454515bf9b08d9eb1d261f%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637799332732347612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yXk7IA4DZj66HIpqWV7oVLE0e3yB1CRK6Q5ZfR5btSs%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWSVTEDBS3NJ2PHASPUW5H3U2E5VHANCNFSM5NYJ7BPA&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C80fa226618454515bf9b08d9eb1d261f%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637799332732347612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jLBhQdzuvp4KCzXWyswl8uK5tYCYk3Q1U1G%2FjLkWE%2FQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C80fa226618454515bf9b08d9eb1d261f%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637799332732347612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PW7tqDx5TGUBAqHZFhGMoJ4ujm2GGlEauyNVHqtTZTg%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C80fa226618454515bf9b08d9eb1d261f%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637799332732347612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZuOyEJoTLjmiOGd1vKDSv%2Bj5NRHRCcufZ3AS97EJr0U%3D&reserved=0>.

**Comment by QuiteAFancyEmerald** [comment]
Why are you opening non HU issues here?

**Comment by hellowpplz** [comment]
Titanium network is responsible for hypertabs creation, is it not??? [cid:c3d48340-a8f7-49a6-82ff-c3b849158f9e]
________________________________
From: Quite A Fancy Emerald ***@***.***>
Sent: Wednesday, February 9, 2022 4:22 AM
To: titaniumnetwork-dev/Holy-Unblocker ***@***.***>
Cc: Student - Barron, Kayden E. ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [titaniumnetwork-dev/Holy-Unblocker] Ah yes this is greay (Issue #281)


Why are you opening non HU issues here?

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftitaniumnetwork-dev%2FHoly-Unblocker%2Fissues%2F281%23issuecomment-1033537080&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C4ac96ab906f242bf78bb08d9ebadb984%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637799953660184538%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vKngYtU3trxUKEzdfK5gstW9GxDHjjVRjm%2BsKywWJc4%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWSVTECTGIQEEIVENDB2JCTU2IW6DANCNFSM5NYJ7BPA&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C4ac96ab906f242bf78bb08d9ebadb984%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637799953660184538%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fQw%2F%2FoeD2i5hzwkFszQJp0Dtx078VJJfHt2ejwCxjvc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C4ac96ab906f242bf78bb08d9ebadb984%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637799953660184538%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cIDEcdai2XiiRPKQ1ixb1cH2MNw4udKrzkOuamBWido%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C4ac96ab906f242bf78bb08d9ebadb984%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637799953660184538%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XVmAs5aLGrgl6g3DsumocnUr2DMmlSBHOgCfx3sVzsA%3D&reserved=0>.
