### ISSUE TITLE
Discord human verification

### ISSUE THREAD

**Issue by cOdEx567** [QuiteAFancyEmerald/HolyUnblockerPublic#284]
One issue that i have ran into is that the discord verification does not work properly. I would like to use it bc it is one of my main comunication methods and i too use it for working in a group proyects. And as for a extra security reason i would like to use this web proxy.

So please could you have a look at it, me and some other people would be very happy

**Comment by MRMRMEATS** [comment]
@cOdEx567 hey. I too have been having this problem. Whenever I go to the proxy and get into the discord it never actually works. I can sign in and then it wants me to use a phone number. (Never actually works, Its a neverending loop of signing in), and it eventually just stops working overall. It was working for about three days after the event, (the event being when all the sites went down and had to be manually restarted), but then I signed in one day and it just stopped. It was the same last year. I might suggest using hypertabs if at all possible. Of course you have to be patient and let it load, (sometimes it doesn't), and then eventually get into discord. Hope they fix this problem soon and good luck on the hypertabs if you're willing to try those.😀

**Comment by s191ed** [comment]
have you been using womginx?

**Comment by QuiteAFancyEmerald** [comment]
UV fixes this issue. #313
