### ISSUE TITLE
Save File problem/Game requests

### ISSUE THREAD

**Issue by MRMRMEATS** [QuiteAFancyEmerald/HolyUnblockerPublic#286]
Hello once again. I might seem to be complaining a lot lately, but this is more of a actual problem than a complaint. So I've been on my pokemon emerald playthrough and I decided to hard save and save in game. After that I went to bed and woke up the next morning and decided to hop back on. I loaded up my hard save file and then booted up my in game file, and it wasn't the last area I was in and I lost a few hours of work. But I figured it could be redone and then I played for about four hours and saved in game and made a hard save as well. I left home for a few hours and then came back, loaded it up and had the same exact problem. Could there by any chance be something wrong with the save feature? Or is it just me.

And here comes my game requests, I'm a big fan of Smash Bros. and Kirby. I was wondering if Super Smash Bros for the N64 could become a HTML5 game? And then any kirby game would be accepted. Preferably the GBA ones as I'm sure its much easier for you guys to add.

**Comment by SubduedCyns** [comment]
Use save states instead of saves, the saves don't work

**Comment by QuiteAFancyEmerald** [comment]
Are you even saving correctly? lol

**Comment by MRMRMEATS** [comment]
> Are you even saving correctly? lol

@QuiteAFancyEmerald  yes I am. I go to the game and save in game first. then I go to saves and click export save.

**Comment by SubduedCyns** [comment]
Use save states and export them
