### ISSUE TITLE
Rammerhead has no url bar

### ISSUE THREAD

**Issue by mistertoenails** [QuiteAFancyEmerald/HolyUnblockerPublic#288]
I have a holyub link, mutualbooks.biz, and the rammerhead proxy has no url bar. Also, if anyone has more proxy links, holy unblocker or other I could really use them.

**Comment by zqpvr** [comment]
same problem i have too

**Comment by s191ed** [comment]
what

**Comment by Nebelung-Dev** [comment]
That might be an beta link. I don't see Rammerhead on the official one

**Comment by hellowpplz** [comment]
(uh) your not supposed to leak link @mistertoenails

**Comment by QuiteAFancyEmerald** [comment]
Indeed. You are supposed to click on either button to navigate you to the RR subdomain. Note that its still in beta.

Lastly Rammerhead is only on newer official HU sites.
