### ISSUE TITLE
Warning for people hosting on Heroku

### ISSUE THREAD

**Issue by vghfr** [QuiteAFancyEmerald/HolyUnblockerPublic#289]
You WILL get suspended eventually for hosting this on heroku (give or take a day after site creation). There's no real way to prevent this, because proxies violate their TOS. Best way to use this is just to host on Replit

**Comment by s191ed** [comment]
i've hosted a proxy and its been up for about 2 months. idk for you but heroku dosent care about my account. if i get banned, oh well its a pretty shitty website to host proxies to begin with

**Comment by nonoguynono** [comment]
i have 5 of them running and they have been for about a year.

**Comment by Nebelung-Dev** [comment]
I would use https://replit.com

**Comment by QuiteAFancyEmerald** [comment]
#250
