### ISSUE TITLE
Unable to join discord servers on womginx

### ISSUE THREAD

**Issue by Imatschoolandeverythingisblockedplshelp** [QuiteAFancyEmerald/HolyUnblockerPublic#290]
I tried joining the TN discord server but it wouldn't let me join. Does anyone know how to fix this?

https://user-images.githubusercontent.com/79165570/153597586-9b64d852-30ae-4b6c-a2c6-d69496d84e70.mp4

**Comment by s191ed** [comment]
invites dont usually work for womginx, recommend using another proxy
