### ISSUE TITLE
So I lied

### ISSUE THREAD

**Issue by hellowpplz** [QuiteAFancyEmerald/HolyUnblockerPublic#293]
So I can access holy unblocker lieraly just now but uhhhh (from womginx) 
![image](https://user-images.githubusercontent.com/94722448/153674744-cbb52371-494b-4ef5-bd98-4ba155e46afe.png)

And corrosion just keeps crashing :/

**Comment by s191ed** [comment]
click on "details" and click on proceed to (domain url).
if that dosent work just type on the website "thisisunsafe" (no theres no textbox, you just have to type it in)

**Comment by hellowpplz** [comment]
Huh, didn't know about the typing thisisunsafe thing...


Cool
________________________________
From: arr3 ***@***.***>
Sent: Friday, February 11, 2022 10:21 PM
To: titaniumnetwork-dev/Holy-Unblocker ***@***.***>
Cc: Student - Barron, Kayden E. ***@***.***>; Author ***@***.***>
Subject: [External] Re: [titaniumnetwork-dev/Holy-Unblocker] So I lied (Issue #293)


click on "details" and click on proceed to (domain url).
if that dosent work just type on the website "thisisunsafe" (no theres no textbox, you just have to type it in)

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftitaniumnetwork-dev%2FHoly-Unblocker%2Fissues%2F293%23issuecomment-1036971763&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C8f7ea2afeafd4324682008d9edd6b3b0%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637802328688317333%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=l3BH9savC4KJbhPyWBlKfsfBxrJArn1rLwpqiDrjRms%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWSVTEHG2QQ34IBE3ZZU4ILU2XG2BANCNFSM5OFNNXCQ&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C8f7ea2afeafd4324682008d9edd6b3b0%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637802328688317333%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VSR%2BBg2bqLexDAIQQ8cNXZr0f%2BZpFayubEIwJRUqEvI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C8f7ea2afeafd4324682008d9edd6b3b0%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637802328688317333%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mfaosp0ga4aFIsb090HZecN26dVkgaPjim9Q1xtcY14%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckaydenbarron%40student.hcps.org%7C8f7ea2afeafd4324682008d9edd6b3b0%7Cc1f6ac536b774db594724f104eeac96a%7C0%7C0%7C637802328688317333%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FvKwk8GZ9oOqVwb%2Bs6EIVgnmCInSCYCyVZ3MF%2BMRiyc%3D&reserved=0>.

**Comment by QuiteAFancyEmerald** [comment]
Domain is gone gone
