### ISSUE TITLE
heroku

### ISSUE THREAD

**Issue by WhyNot-0538** [QuiteAFancyEmerald/HolyUnblockerPublic#297]
so when I try to log in to heroku it refreshes every time I try to login

**Comment by BumiM08** [comment]
Your Heroku account was disabled for using proxys, proxys are against its TOS

**Comment by WhyNot-0538** [comment]
is there a way to fix this?

**Comment by ghost** [comment]
> is there a way to fix this?

No, the only way is to remove everything that makes HU what it is and what it does (in short: removing proxy code)
which makes HU into nothing

**Comment by QuiteAFancyEmerald** [comment]
Read the pinned issues
