### ISSUE TITLE
Will Not load

### ISSUE THREAD

**Issue by LuchaTheAI** [QuiteAFancyEmerald/HolyUnblockerPublic#298]
So when I try to open Holy Unblocker the tab I opened it in loads indefinitely and when it does finally load, if it does, it will not let me in. Any way I can fix that

**Comment by LuchaTheAI** [comment]
I have tried reloading it it just does the same thing that I talked about above.

**Comment by hellowpplz** [comment]
The bug from before is still happening- Emerald has 100+ links to update lol

Also delete the image, your leaking domains (url's) for it. They are supposed to go to the discord for it.
