### ISSUE TITLE
Rammerhead proxy options lead to errors/dead links

### ISSUE THREAD

**Issue by Tert1143** [QuiteAFancyEmerald/HolyUnblockerPublic#300]
Whenever I attempt to use Rammerhead on its page on HUB, both options fail to really do much of anything. Using the Stealth option brings me to the "SITE.com refused to connect" page, little note dude and all. The Classic option leads to a different page, but displays a client error from CloudFlare stating that an SSL handshake was failed, with the error code 525. I'm not all too fluent with git, I had to make a new account entirely to post this issue, so please pardon me if my experience is a bit lacking. Thanks for reading, and I can supply as many error-based details as I can. Have a good one.

**Comment by QuiteAFancyEmerald** [comment]
You are not on a official or recent site
