### ISSUE TITLE
Mario and Luigi Superstar Saga

### ISSUE THREAD

**Issue by Senshi209** [QuiteAFancyEmerald/HolyUnblockerPublic#302]
Can we add mario and luigi superstar saga for holy unblocked? its a cool gba RPG that would make a great addition to the EmuLibrary and Chrono Trigger

**Comment by kingof985** [comment]
This is page is used for reporting issues  with hu not for game requests

**Comment by Senshi209** [comment]
Oh, and also Chrono Trigger(SNES) is pretty good.
