### ISSUE TITLE
Ultra-violet is ass

### ISSUE THREAD

**Issue by hellowpplz** [QuiteAFancyEmerald/HolyUnblockerPublic#303]
Ultra-violet is ass, that's all I will say this time. No matter what url I use it brings me here

![image](https://user-images.githubusercontent.com/94722448/154820362-c302a2d4-1a3c-4ab4-95e8-17f64f3117da.png)

*Later...* I try it again and it brings me to a blue screen ( I am using https://now.gg/play/roblox-corporation/5349/roblox/?utm_campaign url), so I try to reload after waiting 5 minutes and it says it redirected me to many times. How many cookies does this use???

Edit: Yes, clearing my cookies worked.

**Comment by Degen-dev** [comment]
Nice issue name lol. Ultraviolet is still in beta as it says on HU. Please consider that it is not fully complete :)

**Comment by QuiteAFancyEmerald** [comment]
#313
