### ISSUE TITLE
found something that can help NDS emulator support

### ISSUE THREAD

**Issue by Senshi209** [QuiteAFancyEmerald/HolyUnblockerPublic#306]
I've been seeing issues asking to add nds emulator support. Good news - I've found a project that may help: https://github.com/44670/desmume-wasm

tested it with metroid prime hunters, works perfectly. Please consider adding this to holy unblocked

Also, found a PS emulator project in browser if it may help: https://github.com/dkoluris/pseudo
Could you add saves to psuedo? Hope these helped.

**Comment by Senshi209** [comment]
Also, i know i said this before but also plz add chrono trigger and superstar saga to emulibrary

**Comment by QuiteAFancyEmerald** [comment]
@BinBashBanana

**Comment by BinBashBanana** [comment]
That looks pretty cool, though all of the emulators use RetroArch. There is a desmume core for retroarch, but it does not work very well, so I'll instead be using [melonDS](https://github.com/libretro/melonDS). Progress is going smoothly, and I can use pthreads too.

**Comment by Senshi209** [comment]
ok thx. and also pls add chrono trigger to emulibrary
