### ISSUE TITLE
Rammerhead doesn't work for me

### ISSUE THREAD

**Issue by Imatschoolandeverythingisblockedplshelp** [QuiteAFancyEmerald/HolyUnblockerPublic#308]
When I try to use rammerhead, it just brings up this error page: 
![Screenshot 2022-02-23 8 35 59 AM](https://user-images.githubusercontent.com/79165570/155330197-5d374278-b35c-4959-97db-64d4a3e0eac5.png)

**Comment by QuiteAFancyEmerald** [comment]
You don't have external proxies setup correctly
