### ISSUE TITLE
Now.gg On web games deosnt work

### ISSUE THREAD

**Issue by kingof985** [QuiteAFancyEmerald/HolyUnblockerPublic#316]
Proof 
![Screenshot 2022-02-26 8 04 28 AM](https://user-images.githubusercontent.com/86267908/155844408-4624948e-8a21-47c6-8d34-88b5c97b7a5e.png)

**Comment by QuiteAFancyEmerald** [comment]
Resolved with the latest update on Holy Unblocker (both public and private). Issue involved the NGINX setup the official sites were using.
