### ISSUE TITLE
Every time I try to use a discord proxy the screen goes white when I click an option

### ISSUE THREAD

**Issue by BrynnMain** [QuiteAFancyEmerald/HolyUnblockerPublic#317]

**Comment by L0stMem** [comment]
Same man

**Comment by ToasterWaffl** [comment]
I think it might be a issue with the proxies in general

**Comment by QuiteAFancyEmerald** [comment]
Make sure you are hosting the proxies if you are self hosting correctly AND navigating through the main site :)
Service workers can be a bit whacky when registering so if you are on ta official site make sure you use on-site navigation to use Discord.
