### ISSUE TITLE
cant deploy?

### ISSUE THREAD

**Issue by piplup7575** [QuiteAFancyEmerald/HolyUnblockerPublic#318]
![image](https://user-images.githubusercontent.com/88395302/156004604-49dbf0ae-adb8-4555-a313-9efd810a79fb.png)

I get this error when deploying through github pages

![image](https://user-images.githubusercontent.com/88395302/156004679-4c6c190f-3fe0-400a-b469-e028a4b51cf6.png)

not sure if thats my side or what

**Comment by QuiteAFancyEmerald** [comment]
GH pages is static hosting only.....

**Comment by piplup7575** [comment]
ok cool im an idiot
