### ISSUE TITLE
How do I setup rammerhead?

### ISSUE THREAD

**Issue by Imatschoolandeverythingisblockedplshelp** [QuiteAFancyEmerald/HolyUnblockerPublic#320]
I don't know how to set up rammerhead. Can someone help me figure this out?

**Comment by QuiteAFancyEmerald** [comment]
Rammerhead's source isn't exactly public. Regarding setup though you can use the public A record Binary Person has provided:

`64.190.90.54`

You also need to be in the Rammerhead Discord for this and use the `/add-public-domain` command in `#bots`.

Rammerhead Discord: [ht️tps⁯://disco️rd.⁬gg/VNT⁢4E7gN5⁦Y](https://discord.gg/VNT4E7gN5Y)

**Comment by ImaginaryNeon** [comment]
> Rammerhead's source isn't exactly public. Regarding setup though you can use the public A record Binary Person has provided:
> 
> `64.190.90.54`
> 
> You also need to be in the Rammerhead Discord for this and use the `/add-public-domain` command in `#bots`.
> 
> Rammerhead Discord: [ht️tps⁯://disco️rd.⁬gg/VNT⁢4E7gN5⁦Y](https://discord.gg/VNT4E7gN5Y)

What about those of us who, you know, need an unblocker for Discord in the first place?

**Comment by Brenden2008** [comment]
> > Rammerhead's source isn't exactly public. Regarding setup though you can use the public A record Binary Person has provided:
> > `64.190.90.54`
> > You also need to be in the Rammerhead Discord for this and use the `/add-public-domain` command in `#bots`.
> > Rammerhead Discord: [ht️tps⁯://disco️rd.⁬gg/VNT⁢4E7gN5⁦Y](https://discord.gg/VNT4E7gN5Y)
> 
> What about those of us who, you know, need an unblocker for Discord in the first place?

Use corrosion temporarily.
