### ISSUE TITLE
Bookmarklets broken

### ISSUE THREAD

**Issue by myswni** [QuiteAFancyEmerald/HolyUnblockerPublic#325]
When I use the Porta Proxy, it says example domain. Is this just me, or is it broken?
![Screenshot 2022-03-04 11 05 57 AM](https://user-images.githubusercontent.com/100964641/156827784-22d5ee0e-2897-4637-a0b9-d73398b54cb6.png)

**Comment by piplup7575** [comment]
you have to change the url in in to use it
