### ISSUE TITLE
"ERR_TOO_MANY_REDIRECTS" on brand new link

### ISSUE THREAD

**Issue by Tert1143** [QuiteAFancyEmerald/HolyUnblockerPublic#328]
After obtaining a brand new link from the TN server, i tried to get the link to run, however every time I attempt to go to the link, it crashes with an "ERR_TOO_MANY_REDIRECTS" error. I've tried clearing both my cookies and cache, and performing a hard refresh, to no avail. Is there a problem with the link? Is there a problem with my PC? What's going on here? I'm happy to provide any additional details, if needed. Thank you in advance!

**Comment by QuiteAFancyEmerald** [comment]
Odd. Is this with the entire site and with Holy Unblocker?

**Comment by Tert1143** [comment]
Yes. Issue persisted for about a day, them fixed itself. Seemed like some sort of issue with a link calling itself too much. 

Thanks for your input, though. Have a good one!
