### ISSUE TITLE
I need help with the dns

### ISSUE THREAD

**Issue by Thewierduser** [QuiteAFancyEmerald/HolyUnblockerPublic#329]
Can anyone help me with adding a custom domain on Railway? I got the domain but can't figure out how to set up the DNS in Cloudflare.

**Comment by Thewierduser** [comment]
this isn't an issue just need help.

**Comment by QuiteAFancyEmerald** [comment]
I'm not sure as I don't really use Railway. Check out the README tho (also note that HU is no longer being worked on by me)
