### ISSUE TITLE
Expired domain

### ISSUE THREAD

**Issue by hellowpplz** [QuiteAFancyEmerald/HolyUnblockerPublic#330]
So if quiteafancyemerald could give me his email that would make this easier, but basically my most used domain got expired by porkbun.com.

Edit
![Screenshot 2022-03-08 4 41 32 PM](https://user-images.githubusercontent.com/94722448/157330173-2273d9e5-d091-42c6-9e81-eb58ed2564f3.png)

**Comment by QuiteAFancyEmerald** [comment]
Domain has expired and is most likely blocked now. Look into joining the TN discord for newer sites
