### ISSUE TITLE
"TypeError: Failed to fetch"

### ISSUE THREAD

**Issue by SubduedCyns** [QuiteAFancyEmerald/HolyUnblockerPublic#335]
![Screenshot 2022-03-10 1 25 09 PM](https://user-images.githubusercontent.com/90992351/157757348-19d68343-085a-4d21-affa-48db60461267.png)
![Screenshot 2022-03-10 12 55 00 PM](https://user-images.githubusercontent.com/90992351/157757410-4e612528-b494-4e10-8b80-2a5f62080bbb.png)
![Screenshot 2022-03-10 12 54 54 PM](https://user-images.githubusercontent.com/90992351/157757419-cd15cb36-bd42-4ca7-9b6e-8f9a22731633.png)

Whenever I try to use the Ultra Violet Proxy, I always get the same message....
Please help?

**Comment by TNT599** [comment]
refresh page

**Comment by SubduedCyns** [comment]
I have tried that many times, always shows the same page.

**Comment by TNT599** [comment]
idk, however HU has been shut down. Use self hosting or find an alternative site

**Comment by QuiteAFancyEmerald** [comment]
Although Holy Unblocker is no longer being worked on by me and this is a super late reply: should be resolved.
