### ISSUE TITLE
All games are broken when deploying with Replit

### ISSUE THREAD

**Issue by TheRealLOTM** [QuiteAFancyEmerald/HolyUnblockerPublic#336]
I deployed Holy Unblocker to Replit and everything is working fine except all the games. I was wondering if there is anyway to fix it. When I click any game it gives me a 404 error.

**Comment by Wire1essboi** [comment]
The same thing has been happening to me as well hopefully it will be patched soon enough.

**Comment by Aleclee2010** [comment]
me to nun of the games work neither do the other proxys

**Comment by QuiteAFancyEmerald** [comment]
Due to piracy concerns everything related to the games library has been moved over to "gfiles" or "HU-Archive" which you can find linked in the README or in my repository list. 

Hope this helps and sorry for the late reply! <3
