### ISSUE TITLE
discord mic not supported on stealth womginx or ultraviolet

### ISSUE THREAD

**Issue by mag-420** [QuiteAFancyEmerald/HolyUnblockerPublic#339]
pretty much just title, i tried everything including giving permissions separately and it didnt seem to do anything. my mic doesn't seem to show up as an input device at all. however, when i test my mic it works for some reason. also as an unrelated topic, my account got banned for spamming when i accessed it from ultraviolet for the first time, idk if that's just a me thing or not

**Comment by devyaanb** [comment]
HU Proxies don't support WebRTC, which is required to use the mic in calls. This might be added in the future though. 

And on the topic of your account getting banned, I believe Womginx is the only proxy that doesn't get your account flagged by Discord.
