### ISSUE TITLE
Rammerhead not working for me

### ISSUE THREAD

**Issue by Quart2629** [QuiteAFancyEmerald/HolyUnblockerPublic#342]
I deployed it to repl and everything else works fine, but not rammerhead. When I click classic and stealth, this is what shows up

![Captur2we](https://user-images.githubusercontent.com/60115192/158003746-4d72840f-d50e-400a-b18f-80a412a0ce97.PNG)
.

**Comment by QuiteAFancyEmerald** [comment]
You need to set that up yourself in the RH discord
