### ISSUE TITLE
Setting up my HU link on Replit, the site isn't working

### ISSUE THREAD

**Issue by devyaanb** [QuiteAFancyEmerald/HolyUnblockerPublic#343]
When I try to set my HU link with Replit using a Freenom domain, it gives a redirect error and the preview in Replit just shows a blank screen.

Error:
![proxy-2](https://user-images.githubusercontent.com/91038438/158069251-34619395-b44f-4f5e-b9f8-dcc296cb4c22.png)

DNS Records:
![proxy](https://user-images.githubusercontent.com/91038438/158069266-290f6dd5-86cd-4174-bf46-c97322c3d646.png)

**Comment by devyaanb** [comment]
I just realized the resolution of the first screenshot is really low so I'll just put the text here.

Safari Can't Open the Page

Too many redirects occurred trying to open "[LINK]". This might occur if you open a page that is redirected to open another page which is then redirected to open the original page.

**Comment by QuiteAFancyEmerald** [comment]
Odd. Did you update all the scripts in /expr correctly?

Also can you send the example site you are using?

**Comment by Firedanger52** [comment]
Replit banned proxys just to let you guys know...
