### ISSUE TITLE
Subdomains

### ISSUE THREAD

**Issue by ZStrikeGit** [QuiteAFancyEmerald/HolyUnblockerPublic#346]
im hosting HU on my own hardware and i cant figure out what the wogminx subdomain DNS records would point to on my server, please help me im so stumped

subdomain example: a.domain.com

**Comment by helloqwerty12345** [comment]
yeah im having the same issue

**Comment by helloqwerty12345** [comment]
i got womginx to work, but not rammerhead since I can't find the code

**Comment by cerebralshape** [comment]
rammerhead code -> https://github.com/binary-person/rammerhead
it was recently made open source.
you would use an A record with "a" which maps traffic to another site/server which you are hosting your site on.
| NAME                 | TYPE | VALUE | RECORD         |
|----------------------|------|-------|----------------|
| a.holyubofficial.net | A    | a     | 123.123.123.12 |
