### ISSUE TITLE
How do I post this in replit, im very new to coding and if you have a youtube video please link it down here

### ISSUE THREAD

**Issue by shahabdagoat** [QuiteAFancyEmerald/HolyUnblockerPublic#349]

**Comment by Zubbbz** [comment]
you literally click the button in the readme that says "Run On Replit" and login with your account when it prompts you. Then Click the Green "Run" button at the top middle of the replit AFTER everything is done installing and setting itself up. You are a helpless idiot. You wont always be spoonfed the answer so don't get used to it.

**Comment by cerebralshape** [comment]
imagine needing a YT vid for this ^^

**Comment by arandomhooman** [comment]
Like, just click the button.
