### ISSUE TITLE
I'm not sure, but how do I appeal to Titanium Network Discord

### ISSUE THREAD

**Issue by MegaTKC** [QuiteAFancyEmerald/HolyUnblockerPublic#351]
Hi, I recently got banned from the Titanium Network discord server. I didn't type anything in any other channel and I just typed in the proxy commands channel to generate a new holy unblocker link. I got banned after I sent links to my friends. Is this a false ban or is there a reason to this? I closed the dm to the response where I got banned, and i'm having trouble finding it.

**Comment by Zubbbz** [comment]
Stop making stupid github issues. Holy Unblocker is not at all in kahoots with Titanium Network. Also if  they banned you, I'm sure they have a good reason. Point is you're stupid, stop misusing GH issues. stay banned idiot.

**Comment by 3L33tmakersUnited** [comment]
RIP. This has to hurt a lot but kinda liked to read it though...

**Comment by MegaTKC** [comment]
> Stop making stupid github issues. Holy Unblocker is not at all in kahoots with Titanium Network. Also if they banned you, I'm sure they have a good reason. Point is you're stupid, stop misusing GH issues. stay banned idiot.

I dont know why. so does sharing links with your friends get you banned?

**Comment by Degen-dev** [comment]
@MegaTKC yes
