### ISSUE TITLE
Geforce now/Games 

### ISSUE THREAD

**Issue by Fruvzz** [QuiteAFancyEmerald/HolyUnblockerPublic#354]
If I try to start up a game I keep getting the same error code i don't know how to fix it the code is 0X00000157 I tried everything in my power but cant fix it. Also minecraft bedrock does not work for me I don't know why. (btw use heroku to launch holy unblocker)
https://user-images.githubusercontent.com/87160201/159334118-1ee6c7ce-22f6-4dac-94ba-a66bcf602883.png
https://user-images.githubusercontent.com/87160201/159334933-cbbd2707-b36a-4fae-9ea6-bfe57b9aa983.png

**Comment by Zubbbz** [comment]
Even if you did manage to start a game through Geforce NOW, the input lag and amount of compression would not make attempting to play anything worthwhile.

**Comment by kingof985** [comment]
> Even if you did manage to start a game through Geforce NOW, the input lag and amount of compression would not make attempting to play anything worthwhile.It is possible to start it up for me it has minimal lag i dont know about you but is possible.
