### ISSUE TITLE
So, now what?

### ISSUE THREAD

**Issue by ImaginaryNeon** [QuiteAFancyEmerald/HolyUnblockerPublic#356]
I'm kinda screwed over by the shutting down of HU because I can't find an alternative, and Discord is blocked... as is Reddit... and like half of the stuff that shows up when I look for the individual proxies...

**Comment by nonoguynono** [comment]
are the hosting services blocked? because if not you can just launch your own

**Comment by ImaginaryNeon** [comment]
> are the hosting services blocked? because if not you can just launch your own

I think so. I tried to deploy with repl.it or whatever and the preivew thing was blocked.

**Comment by sugarbabylol** [comment]
do there is any other links like holy unblocker?? because idk what to do rn.

**Comment by Rockpods** [comment]
The Discord bot has been reset, so you can get new links. I suggest you request Incognito.

**Comment by sugarbabylol** [comment]
> The Discord bot has been reset, so you can get new links. I suggest you request Incognito.

where tho.

**Comment by devyaanb** [comment]
> where tho.

Official Discord Server for Titanium Network and its proxies (Hypertabs, Incognito, formally HU) [https://discord.gg/unblock](https://discord.gg/unblock)

**Comment by 869066** [comment]
> > where tho.
> 
> https://discord.gg/unblock

That's the official Discord server for TN Proxies

**Comment by sugarbabylol** [comment]
> > where tho.
> 
> Official Discord Server for Titanium Network and it's proxies (Hypertabs, Incognito, formally HU) https://discord.gg/unblock

i need someone to send me link because i dont have my phone on me lmfaooo.

**Comment by Zubbbz** [comment]
the creator made this for free and does not owe anyone anything. people like you are why they stopped development. stop making issues on this repo complaining about things that Emerald cant solve. There are many ways to host it yourself made super easy with the buttons in the readme. Some other alternative will pop up sooner or later. titanium network is great. stop bitching. This is not the place to ask for an alternative. Github issues are so bugs, issues, and new ideas can be reported to the developer, not for you to complain.

**Comment by ImaginaryNeon** [comment]
> > where tho.
> 
> Official Discord Server for Titanium Network and its proxies (Hypertabs, Incognito, formally HU) https://discord.gg/unblock

Problem with that is it needs phone verification and I don't have a phone. (Also, I have to use the unblocker to access the Discord, so the Double Counter thing is in my way)

**Comment by nonoguynono** [comment]
> > where tho.
> 
> Official Discord Server for Titanium Network and its proxies (Hypertabs, Incognito, formally HU) https://discord.gg/unblock

how do i request an inconito link? i know that requesting hu links used to be %HU, but is it different for other links?

**Comment by cerebralshape** [comment]
> 

make a phone number with google phone?
conversation should move to the official discord instead of this repository

**Comment by arandomhooman** [comment]
Just use ultraviolet and host it on replit
