### ISSUE TITLE
Uhhhhhm guuuuuuys?

### ISSUE THREAD

**Issue by hellowpplz** [QuiteAFancyEmerald/HolyUnblockerPublic#360]
Have ANYONE else noticed that the website is working again??? Theeeeee FRICK?

**Comment by 3L33tmakersUnited** [comment]
Welp. That is actually interesting.

**Comment by Alvin-He** [comment]
don't look like anybody's maintaining the repo tho
maybe they're only maintaining the site???!

**Comment by kingof985** [comment]
balls

**Comment by QuiteAFancyEmerald** [comment]
Nope. More information about the future of Holy Unblocker to be announced. Just know that I will not have a part in it :)

**Comment by hellowpplz** [comment]
Welp, it was good to be a part of this github and to be able to contribute on actually almost a weekly basis. So all I can say is thank you for everything Em.  (Also that means there IIIIS a future ah haaaaaaaah)
________________________________
From: Quite A Fancy Emerald ***@***.***>
Sent: Wednesday, March 30, 2022 2:08 AM
To: QuiteAFancyEmerald/Holy-Unblocker-Old ***@***.***>
Cc: Student - Barron, Kayden E. ***@***.***>; Author ***@***.***>
Subject: [External] Re: [QuiteAFancyEmerald/Holy-Unblocker-Old] Uhhhhhm guuuuuuys? (Issue #360)


Nope. More information about the future of Holy Unblocker to be announced. Just know that I will not have a part in it :)
