### ISSUE TITLE
I cant  Access insta through the womginx proxi

### ISSUE THREAD

**Issue by 3laf0** [QuiteAFancyEmerald/HolyUnblockerPublic#363]

**Comment by 3L33tmakersUnited** [comment]
Well sadly, its not his problem because if you have been paying attention, it's been discontinued so its really no use opening stuff like this.

**Comment by cerebralshape** [comment]
womginx is a separate proxy located at -> https://github.com/binary-person/womginx
problems with womginx should go there.
