### ISSUE TITLE
the emulators and the emulibrary games dont work  for me are the emu library games file download links?

### ISSUE THREAD

**Issue by ashyboiii** [QuiteAFancyEmerald/HolyUnblockerPublic#366]
![image](https://user-images.githubusercontent.com/91156854/164739385-5e02e8f7-4b19-4af3-a88e-15d12c225604.png)
![Screenshot 2022-04-22 9 52 28 AM](https://user-images.githubusercontent.com/91156854/164739503-bfac06ba-b864-4353-b29f-16ea3b512524.png)

**Comment by ashyboiii** [comment]
oh nvm i just saw they werent featured in the public version

**Comment by ashyboiii** [comment]
wait nvm it still doesn work how do i fix this?

**Comment by QuiteAFancyEmerald** [comment]
Check out HU-Archive!

**Comment by QuiteAFancyEmerald** [comment]
https://github.com/QuiteAFancyEmerald/HU-Archive
