### ISSUE TITLE
Ultraviolet 

### ISSUE THREAD

**Issue by Justh3r3forFun** [QuiteAFancyEmerald/HolyUnblockerPublic#368]
I would like to tell you that ultraviolet stop working for school use for some reason. I know it is not really supposed to be used for school use and all but there are a lot of people out there looking forward to you fixing ultraviolet(like myself). If you would consider fixing it I would be thankful.

Oh and keep up the good work. Don't allow other people and what they say to stop you from doing what you do best because that's what's going to stop you from a lot of things in life:)

your friend,
        Justh3r3forFun

**Comment by QuiteAFancyEmerald** [comment]
Should be alright now?
