### ISSUE TITLE
No longer posting mirror links on review sites?

### ISSUE THREAD

**Issue by russianjesus52** [QuiteAFancyEmerald/HolyUnblockerPublic#371]
have i just been missing them or have you stopped posting them? ive checked 5-6 times recently, because the link that i had been using for about a year now was caught. any way you could get me a link?

**Comment by 3L33tmakersUnited** [comment]
yea I could get ya links. Just tell me if you want a specific end like .org or .uk or something.

**Comment by 3L33tmakersUnited** [comment]
Nvm I gotchu: [press me for link](www.privatesurf.net) It only has one link btw.

**Comment by 3L33tmakersUnited** [comment]
sorry, actually just take the link. www.privatesurf.net

**Comment by QuiteAFancyEmerald** [comment]
Check out the README! Basically I am no longer working on Holy Unblocker as it has new maintainers now (left the community due to drama, etc.). They will soon be doing changes which will make this noticeable :D
