### ISSUE TITLE
Running HU on bare metal results in error

### ISSUE THREAD

**Issue by atomtables** [QuiteAFancyEmerald/HolyUnblockerPublic#372]
Everytime I run HU on my chromebook under crostini(linux), it throws this error:

_______@penguin:______Holy-Unblocker$ npm start

> holyub@5.0.0 start
> node backend.js

(node:5291) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
(node:5291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by QuiteAFancyEmerald** [comment]
Make sure you are using the latest version of Node. Chromebook moments.... :D

**Comment by atomtables** [comment]
ok thx
