### ISSUE TITLE
Heroku app error

### ISSUE THREAD

**Issue by Bascately** [QuiteAFancyEmerald/HolyUnblockerPublic#373]
So when i try to deploy herokuapp saids that ¨Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.¨ and I already made my own fork and it still comes up with the same error and That is my main issue.

**Comment by Justh3r3forFun** [comment]
That's happening to me too

**Comment by QuiteAFancyEmerald** [comment]
#250
