### ISSUE TITLE
Add support for Ultraviolet Google Sign-In.

### ISSUE THREAD

**Issue by Saul5662** [QuiteAFancyEmerald/HolyUnblockerPublic#376]
Basically whenever you try to login with google with UV you will get the unsupported/insecure browser error. Is there anyway you could bypass this somehow?

**Comment by illusionTBA** [comment]
Currently there is no proxy that can do this but i have heard that google logins sometime work with rammerhead

**Comment by QuiteAFancyEmerald** [comment]
Yeah it isn't exactly a prioritized thing. Hammerhead can do so to an extent.
