### ISSUE TITLE
UV proxy doesnt work.

### ISSUE THREAD

**Issue by Altablekez** [QuiteAFancyEmerald/HolyUnblockerPublic#377]
This is across all sites, it says "TypeError: Failed to Fetch" . No matter what site, it is always like this. Is there a reason, or did my school do something

**Comment by insgah** [comment]
![Screenshot 2022-08-09 10 25 22 PM](https://user-images.githubusercontent.com/94826400/183822302-5b6dfdf9-1b14-478c-90ca-89dc44428063.png)
For me, it says this.

**Comment by NVB9ALT** [comment]
I've noticed the same thing

**Comment by windowmandav** [comment]
read discord its shut down for a while

**Comment by QuiteAFancyEmerald** [comment]
Resolved
