### ISSUE TITLE
Setting up in terminal gives error

### ISSUE THREAD

**Issue by proJM-Coding** [QuiteAFancyEmerald/HolyUnblockerPublic#386]
I am trying to run holy unblocker through the terminal and everything works until I try to use an app or proxy. I get this error:

`RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].`

I'm not sure what it means and I have not changed the code at all. Can someone help?

**Comment by FancyBoiL1** [comment]
Is it static? When it is static most proxies will error out.

**Comment by ghost** [comment]
I think so, I'm trying to use github codespaces.
