### ISSUE TITLE
Alternative link

### ISSUE THREAD

**Issue by Reloadandtryagain** [QuiteAFancyEmerald/HolyUnblockerPublic#396]
Hi. Could you create alternative links for this?
If there is any alt links may have them?
Thanks

**Comment by TestingUser1000** [comment]
[](https://d7vyts-8080.csb.app/)

**Comment by Reloadandtryagain** [comment]
I tried it and it did the same thing. Try checking the code on the website and the forked link you created. If you still have trouble I can do this myself and do it too. But thanks for trying anyways

**Comment by TestingUser1000** [comment]
I did check it over with other people and it still gives me the error?

**Comment by QuiteAFancyEmerald** [comment]
Join the TN discord
