### ISSUE TITLE
Error With Forking Website

### ISSUE THREAD

**Issue by TestingUser1000** [QuiteAFancyEmerald/HolyUnblockerPublic#397]
https://d7vyts-8080.csb.app/ this is my proxy that I originally forked it worked great but I suddenly got

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

Does this mean that my server somehow crashed? Or it dosen´t read it right?
Here is the other website https://codesandbox.io/p/github/TestingUser1000/Holy-Unblocker/master?workspaceId=a7c1f978-fa2e-428d-8d09-a37936887658&file=%2FREADME.md

**Comment by QuiteAFancyEmerald** [comment]
Apologies I do not know much about the deployment method above I would recommend shifting over to something else
