### ISSUE TITLE
unblockers won't work

### ISSUE THREAD

**Issue by legendcuzican13** [QuiteAFancyEmerald/HolyUnblockerPublic#398]
This happens when I try to use the unblockers:

![image](https://user-images.githubusercontent.com/108838775/235208951-ff976841-b998-46bf-bb33-4cd67d9bc22d.png)

I deployed the unblocked on my VPS using the following commands 

```git clone https://github.com/titaniumnetwork-dev/Holy-Unblocker.git

cd Holy-Unblocker

npm install

npm start

I've tried all the fixes on the FAQ page with no success.

**Comment by QuiteAFancyEmerald** [comment]
Please ensure that you are using a reverse proxy such as NGINX or caddy with Holy Unblocker
