### ISSUE TITLE
idrk how to get it to work

### ISSUE THREAD

**Issue by smileyfacelol** [QuiteAFancyEmerald/HolyUnblockerPublic#399]
i put in the package.json thing and im new to this so i cant figure it out lol TvT

**Comment by smileyfacelol** [comment]
or...well where do i get the unblocker

**Comment by QuiteAFancyEmerald** [comment]
You need to install git and clone the repository. Ensure that you have npm installed as well.

https://github.com/QuiteAFancyEmerald/Holy-Unblocker#workspace-configurations

**Comment by SoggyCheerio556** [comment]
What does any of this mean gng im js trynna play games at school vro
