### ISSUE TITLE
cloudflare issue...

### ISSUE THREAD

**Issue by verzide-pixel** [QuiteAFancyEmerald/HolyUnblockerPublic#406]
![Screenshot 2024-08-15 8 32 57 AM](https://github.com/user-attachments/assets/8e9b1bb6-9a50-41de-8367-54819ca4dc98)
 
![Screenshot 2024-08-15 8 32 41 AM](https://github.com/user-attachments/assets/70efb061-3248-4353-90ff-3f6dd0d3452d)

**Comment by proudparrot2** [comment]
This is unrelated to the holy unblocker repository - this is something to ask in the [titanium network discord server](https://discord.gg/unblock)

**Comment by QuiteAFancyEmerald** [comment]
No no I consider this a valid issue lmao

HU LTS on the official site was down momentarily as I was away from home (still am) and for some reason auto billing did not work. Issue should be resolved now however update me if needed.
