### ISSUE TITLE
"Banned Dependency Detected!" Railway Deployment

### ISSUE THREAD

**Issue by Kevinzc10** [QuiteAFancyEmerald/HolyUnblockerPublic#407]
Ive tried deploying to Railway, but it Keeps stopping and "Banned Dependency Detected!" Whats up with that?

**Comment by proudparrot2** [comment]
It's because Holy Unblocker has Ultraviolet listed as a dependency, which Railway doesn't allow

**Comment by Kevinzc10** [comment]
Is there any other way i can deploy this, everything else is not working

**Comment by Kevinzc10** [comment]
> It's because Holy Unblocker has Ultraviolet listed as a dependency, which Railway doesn't allow

Is there any other way i can deploy this, everything else is not working

**Comment by proudparrot2** [comment]
Most likely not due to the widespread knowledge of Ultraviolet and it being a proxy service. The most ideal option would be to selfhost Holy Unblocker on your own infrastructure by purchasing a VPS, but I get that some people might not be able to afford it or know how to set it up.

**Comment by Kevinzc10** [comment]
Thank you
