### ISSUE TITLE
weird issue

### ISSUE THREAD

**Issue by zqpvr** [QuiteAFancyEmerald/HolyUnblockerPublic#413]
URL {
  href: 'http://0.0.0.0:8080/',
  origin: 'http://0.0.0.0:8080',
  protocol: 'http:',
  username: '',
  password: '',
  host: '0.0.0.0:8080',
  hostname: '0.0.0.0',
  port: '8080',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
Something broke... ReferenceError: crypto is not defined
    at file:///home/user/Holy-Unblocker/src/server.mjs:262:17

**Comment by QuiteAFancyEmerald** [comment]
Explain the steps to reproduce this

**Comment by zqpvr** [comment]
```
git clone --recurse-submodules https://github.com/titaniumnetwork-dev/Holy-Unblocker.git

cd Holy-Unblocker

npm start
```
this happened on debian 12.7 for me.

**Comment by QuiteAFancyEmerald** [comment]
Are you using Node v20?

**Comment by ydrk** [comment]
> Are you using Node v20?

how often do you touch yourself

**Comment by zqpvr** [comment]
Using node v18.19.0

**Comment by QuiteAFancyEmerald** [comment]
Try using nvm to update to Node v20; then run npm install and npm run build before running npm start

**Comment by zqpvr** [comment]
```
URL {
  href: 'http://127.0.0.1:8080/',
  origin: 'http://127.0.0.1:8080',
  protocol: 'http:',
  username: '',
  password: '',
  host: '127.0.0.1:8080',
  hostname: '127.0.0.1',
  port: '8080',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
Holy Unblocker is listening on port 8080.
Something broke... Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (node:net:1812:16)
    at listenInCluster (node:net:1860:12)
    at doListen (node:net:2009:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080
}
```
I get this when trying to edit src/config.js and putting 127.0.0.1:8085 into the host variable

**Comment by QuiteAFancyEmerald** [comment]
You don't touch `src/config.js` for the port; keep it as 0.0.0.0

`./ecosystem.config.js` has a port option that is used; change that to 8085 for both

**Comment by QuiteAFancyEmerald** [comment]
I realize the README was not updated to reflect that; I have fixed that problem

**Comment by zqpvr** [comment]
`Error: there are no bare clients`
ultravoilet gives this for some reason. but rammerhead works fine

**Comment by zqpvr** [comment]
> `Error: there are no bare clients` ultraviolet gives this for some reason. but rammerhead works fine

when using production mode I get this for ultraviolet
`TypeError: this.port.postMessage is not a function`

**Comment by zqpvr** [comment]
also unrelated but you should update ruffle in flash games, it's very old.

**Comment by zqpvr** [comment]
it works with libcurl, hm some websites don't load though.

**Comment by QuiteAFancyEmerald** [comment]
Ensure you are not using bare server; use either libcurl or epoxy 👍 

> TypeError: this.port.postMessage is not a function

Just reload the page when this happens its an issue with Ultraviolet. Also depending on your reverse proxy setup (nginx, etc.) some sites may not work or be supported. What sites are not loading?

As for the flash games part yeah you are correct. HU LTS isn't released yet so the games TODO tasks are not complete so the majority of the site is still v5

**Comment by zqpvr** [comment]
should I switch the git branch to v5.5?

**Comment by QuiteAFancyEmerald** [comment]
No not at all its outdated

**Comment by zqpvr** [comment]
alright well thank you
