### ISSUE TITLE
ultraviolet stealth not working

### ISSUE THREAD

**Issue by verzide-pixel** [QuiteAFancyEmerald/HolyUnblockerPublic#416]
[Screen recording 2024-10-11 10.42.26 PM.webm](https://github.com/user-attachments/assets/d8d2474f-57e2-46cf-906f-cb616db1764d)

**Comment by verzide-pixel** [comment]
I don't know what is going on if someone can give me advice please do.

**Comment by QuiteAFancyEmerald** [comment]
Try doing Ctrl+Shift+R a few times on the homepage then try again; let me know if the same issue persists.

Is this on a self hosted version of HU LTS or on the official website?

**Comment by verzide-pixel** [comment]
oh thank you so much emerald I'll close it now
