### ISSUE TITLE
Freenom was shut down, no new members available.

### ISSUE THREAD

**Issue by PrimeKidMN** [QuiteAFancyEmerald/HolyUnblockerPublic#418]
The title says it all. Is there another way to get domains for free?

**Comment by QuiteAFancyEmerald** [comment]
Sadly I do not know of a method. Back in the day I remember searching this same thing up on Reddit but I don't remember the post. Hopefully this points you in the right direction.

**Comment by PrimeKidMN** [comment]
I did find one that I think works in some scenarios, but I did not make it. I saw someone use it for rammerhead but it was called dns afraid. or like afraid.dns. Not very good quality but it works.
