### ISSUE TITLE
Iframing blocked across sites (FIX)

### ISSUE THREAD

**Issue by gogo6211** [QuiteAFancyEmerald/HolyUnblockerPublic#423]
I am hosting for free at Koyeb and am going to iframe the long free subdomain URL into my games website but Iframes are blocked in some way (snippet probably encoded) and I am hoping a dev can point me to where it is hidden within the code. Already spent about 1 hour searching for anything related to iframes, base64, etc., and couldn't find anything relating to it besides stuff in the Ultraviolet or Rammerhead folders (which I am 99% sure aren't causing this as the home page of hu I am hosting won't iframe).
*edit I am using 6.3 production btw and just finished briefly skimming all the files and didn't find anything :(

**Comment by QuiteAFancyEmerald** [comment]
You can't iframe crossorigin sites hosted on a domain like Koyeb (they have that disabled);  a common internet practice used on the majority of sites so no place for that. You could host it yourself where you can manage the headers to allow crossorigin iframe usage or iframe one of the official domains (well I believe I have that disabled as well)

**Comment by QuiteAFancyEmerald** [comment]
Actually I flat out lied perhaps this is allowed on Koyeb as a subdomain. Try this first:

https://github.com/QuiteAFancyEmerald/Holy-Unblocker/blob/fea9f9ebd48c4145c90cff47583fa12187b4ab92/src/server.mjs#L111

Edit this function here that utilizes helmet to apply/remove those headers preventing it from being iframed.

```js
app.register(fastifyHelmet, {
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"],
      frameAncestors: ["*"], 
    },
  },
  xFrameOptions: false, 
  xPoweredBy: false,
});
```

**Comment by gogo6211** [comment]
Thanks that worked

**Comment by ghost** [comment]
how do I edit it? please bro i need this

**Comment by gogo6211** [comment]
Fork it then edit line 111 with the snipit above in src/server.mjs in a ide (vs code web works with github remote repo) then deploy your fork to koyeb. If you still don't get it ask chatgpt for help. :)

**Comment by gogo6211** [comment]
> how do I edit it? please bro i need this

Fork it then edit line 111 with the snipit above in src/server.mjs in a ide (vs code web works with github remote repo) then deploy your fork to koyeb. If you still don't get it ask chatgpt for help. :)

**Comment by ghost** [comment]
can i have the github link to yours so I can simply fork that? i tried and it didn't work
