### ISSUE TITLE
Is this project on koyeb iframe protected?

### ISSUE THREAD

**Issue by ghost** [QuiteAFancyEmerald/HolyUnblockerPublic#424]
if so can i disable it and how?

**Comment by QuiteAFancyEmerald** [comment]
#423

**Comment by ghost** [comment]
we talked, and while experamenting i noticed that when it was iframed on a website, it loaded, but when it was framed in a .HTML doc on my desktop, to didn't link. i hosted it on a website, then iframed that and it still didn't work

**Comment by ghost** [comment]
nvm, I deleted the entire part and it worked!  imma give you and the guy on #423 a special thanks on my site! again, appreciate it!
